// Code generated by ent, DO NOT EDIT.

package grove

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldSlug, v))
}

// GitRemote applies equality check predicate on the "git_remote" field. It's identical to GitRemoteEQ.
func GitRemote(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldGitRemote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldCreatedBy, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldOwnerID, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldVisibility, v))
}

// DefaultRuntimeBrokerID applies equality check predicate on the "default_runtime_broker_id" field. It's identical to DefaultRuntimeBrokerIDEQ.
func DefaultRuntimeBrokerID(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldDefaultRuntimeBrokerID, v))
}

// GithubInstallationID applies equality check predicate on the "github_installation_id" field. It's identical to GithubInstallationIDEQ.
func GithubInstallationID(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldGithubInstallationID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContainsFold(FieldSlug, v))
}

// GitRemoteEQ applies the EQ predicate on the "git_remote" field.
func GitRemoteEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldGitRemote, v))
}

// GitRemoteNEQ applies the NEQ predicate on the "git_remote" field.
func GitRemoteNEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldGitRemote, v))
}

// GitRemoteIn applies the In predicate on the "git_remote" field.
func GitRemoteIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldGitRemote, vs...))
}

// GitRemoteNotIn applies the NotIn predicate on the "git_remote" field.
func GitRemoteNotIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldGitRemote, vs...))
}

// GitRemoteGT applies the GT predicate on the "git_remote" field.
func GitRemoteGT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldGitRemote, v))
}

// GitRemoteGTE applies the GTE predicate on the "git_remote" field.
func GitRemoteGTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldGitRemote, v))
}

// GitRemoteLT applies the LT predicate on the "git_remote" field.
func GitRemoteLT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldGitRemote, v))
}

// GitRemoteLTE applies the LTE predicate on the "git_remote" field.
func GitRemoteLTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldGitRemote, v))
}

// GitRemoteContains applies the Contains predicate on the "git_remote" field.
func GitRemoteContains(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContains(FieldGitRemote, v))
}

// GitRemoteHasPrefix applies the HasPrefix predicate on the "git_remote" field.
func GitRemoteHasPrefix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasPrefix(FieldGitRemote, v))
}

// GitRemoteHasSuffix applies the HasSuffix predicate on the "git_remote" field.
func GitRemoteHasSuffix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasSuffix(FieldGitRemote, v))
}

// GitRemoteIsNil applies the IsNil predicate on the "git_remote" field.
func GitRemoteIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldGitRemote))
}

// GitRemoteNotNil applies the NotNil predicate on the "git_remote" field.
func GitRemoteNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldGitRemote))
}

// GitRemoteEqualFold applies the EqualFold predicate on the "git_remote" field.
func GitRemoteEqualFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEqualFold(FieldGitRemote, v))
}

// GitRemoteContainsFold applies the ContainsFold predicate on the "git_remote" field.
func GitRemoteContainsFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContainsFold(FieldGitRemote, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldLabels))
}

// AnnotationsIsNil applies the IsNil predicate on the "annotations" field.
func AnnotationsIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldAnnotations))
}

// AnnotationsNotNil applies the NotNil predicate on the "annotations" field.
func AnnotationsNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldAnnotations))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContainsFold(FieldCreatedBy, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldOwnerID))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContainsFold(FieldOwnerID, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.Grove {
	return predicate.Grove(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.Grove {
	return predicate.Grove(sql.FieldContainsFold(FieldVisibility, v))
}

// DefaultRuntimeBrokerIDEQ applies the EQ predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDEQ(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldDefaultRuntimeBrokerID, v))
}

// DefaultRuntimeBrokerIDNEQ applies the NEQ predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDNEQ(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldDefaultRuntimeBrokerID, v))
}

// DefaultRuntimeBrokerIDIn applies the In predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDIn(vs ...uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldDefaultRuntimeBrokerID, vs...))
}

// DefaultRuntimeBrokerIDNotIn applies the NotIn predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDNotIn(vs ...uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldDefaultRuntimeBrokerID, vs...))
}

// DefaultRuntimeBrokerIDGT applies the GT predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDGT(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldDefaultRuntimeBrokerID, v))
}

// DefaultRuntimeBrokerIDGTE applies the GTE predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDGTE(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldDefaultRuntimeBrokerID, v))
}

// DefaultRuntimeBrokerIDLT applies the LT predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDLT(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldDefaultRuntimeBrokerID, v))
}

// DefaultRuntimeBrokerIDLTE applies the LTE predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDLTE(v uuid.UUID) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldDefaultRuntimeBrokerID, v))
}

// DefaultRuntimeBrokerIDIsNil applies the IsNil predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldDefaultRuntimeBrokerID))
}

// DefaultRuntimeBrokerIDNotNil applies the NotNil predicate on the "default_runtime_broker_id" field.
func DefaultRuntimeBrokerIDNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldDefaultRuntimeBrokerID))
}

// SharedDirsIsNil applies the IsNil predicate on the "shared_dirs" field.
func SharedDirsIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldSharedDirs))
}

// SharedDirsNotNil applies the NotNil predicate on the "shared_dirs" field.
func SharedDirsNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldSharedDirs))
}

// GithubInstallationIDEQ applies the EQ predicate on the "github_installation_id" field.
func GithubInstallationIDEQ(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDNEQ applies the NEQ predicate on the "github_installation_id" field.
func GithubInstallationIDNEQ(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldNEQ(FieldGithubInstallationID, v))
}

// GithubInstallationIDIn applies the In predicate on the "github_installation_id" field.
func GithubInstallationIDIn(vs ...int64) predicate.Grove {
	return predicate.Grove(sql.FieldIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDNotIn applies the NotIn predicate on the "github_installation_id" field.
func GithubInstallationIDNotIn(vs ...int64) predicate.Grove {
	return predicate.Grove(sql.FieldNotIn(FieldGithubInstallationID, vs...))
}

// GithubInstallationIDGT applies the GT predicate on the "github_installation_id" field.
func GithubInstallationIDGT(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldGT(FieldGithubInstallationID, v))
}

// GithubInstallationIDGTE applies the GTE predicate on the "github_installation_id" field.
func GithubInstallationIDGTE(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldGTE(FieldGithubInstallationID, v))
}

// GithubInstallationIDLT applies the LT predicate on the "github_installation_id" field.
func GithubInstallationIDLT(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldLT(FieldGithubInstallationID, v))
}

// GithubInstallationIDLTE applies the LTE predicate on the "github_installation_id" field.
func GithubInstallationIDLTE(v int64) predicate.Grove {
	return predicate.Grove(sql.FieldLTE(FieldGithubInstallationID, v))
}

// GithubInstallationIDIsNil applies the IsNil predicate on the "github_installation_id" field.
func GithubInstallationIDIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldGithubInstallationID))
}

// GithubInstallationIDNotNil applies the NotNil predicate on the "github_installation_id" field.
func GithubInstallationIDNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldGithubInstallationID))
}

// GithubPermissionsIsNil applies the IsNil predicate on the "github_permissions" field.
func GithubPermissionsIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldGithubPermissions))
}

// GithubPermissionsNotNil applies the NotNil predicate on the "github_permissions" field.
func GithubPermissionsNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldGithubPermissions))
}

// GithubAppStatusIsNil applies the IsNil predicate on the "github_app_status" field.
func GithubAppStatusIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldGithubAppStatus))
}

// GithubAppStatusNotNil applies the NotNil predicate on the "github_app_status" field.
func GithubAppStatusNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldGithubAppStatus))
}

// GitIdentityIsNil applies the IsNil predicate on the "git_identity" field.
func GitIdentityIsNil() predicate.Grove {
	return predicate.Grove(sql.FieldIsNull(FieldGitIdentity))
}

// GitIdentityNotNil applies the NotNil predicate on the "git_identity" field.
func GitIdentityNotNil() predicate.Grove {
	return predicate.Grove(sql.FieldNotNull(FieldGitIdentity))
}

// HasAgents applies the HasEdge predicate on the "agents" edge.
func HasAgents() predicate.Grove {
	return predicate.Grove(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentsTable, AgentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentsWith applies the HasEdge predicate on the "agents" edge with a given conditions (other predicates).
func HasAgentsWith(preds ...predicate.Agent) predicate.Grove {
	return predicate.Grove(func(s *sql.Selector) {
		step := newAgentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Grove) predicate.Grove {
	return predicate.Grove(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Grove) predicate.Grove {
	return predicate.Grove(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Grove) predicate.Grove {
	return predicate.Grove(sql.NotPredicates(p))
}
