// Code generated by ent, DO NOT EDIT.

package subscriptiontemplate

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscriptiontemplate type in the database.
	Label = "subscription_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldTriggerActivities holds the string denoting the trigger_activities field in the database.
	FieldTriggerActivities = "trigger_activities"
	// FieldGroveID holds the string denoting the grove_id field in the database.
	FieldGroveID = "grove_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// Table holds the table name of the subscriptiontemplate in the database.
	Table = "subscription_templates"
)

// Columns holds all SQL columns for subscriptiontemplate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldScope,
	FieldTriggerActivities,
	FieldGroveID,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultScope holds the default value on creation for the "scope" field.
	DefaultScope string
	// DefaultGroveID holds the default value on creation for the "grove_id" field.
	DefaultGroveID string
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
)

// OrderOption defines the ordering options for the SubscriptionTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByTriggerActivities orders the results by the trigger_activities field.
func ByTriggerActivities(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerActivities, opts...).ToFunc()
}

// ByGroveID orders the results by the grove_id field.
func ByGroveID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroveID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}
