// Code generated by ent, DO NOT EDIT.

package subscriptiontemplate

import (
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldName, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldScope, v))
}

// TriggerActivities applies equality check predicate on the "trigger_activities" field. It's identical to TriggerActivitiesEQ.
func TriggerActivities(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldTriggerActivities, v))
}

// GroveID applies equality check predicate on the "grove_id" field. It's identical to GroveIDEQ.
func GroveID(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldGroveID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContainsFold(FieldName, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContainsFold(FieldScope, v))
}

// TriggerActivitiesEQ applies the EQ predicate on the "trigger_activities" field.
func TriggerActivitiesEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldTriggerActivities, v))
}

// TriggerActivitiesNEQ applies the NEQ predicate on the "trigger_activities" field.
func TriggerActivitiesNEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNEQ(FieldTriggerActivities, v))
}

// TriggerActivitiesIn applies the In predicate on the "trigger_activities" field.
func TriggerActivitiesIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldIn(FieldTriggerActivities, vs...))
}

// TriggerActivitiesNotIn applies the NotIn predicate on the "trigger_activities" field.
func TriggerActivitiesNotIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNotIn(FieldTriggerActivities, vs...))
}

// TriggerActivitiesGT applies the GT predicate on the "trigger_activities" field.
func TriggerActivitiesGT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGT(FieldTriggerActivities, v))
}

// TriggerActivitiesGTE applies the GTE predicate on the "trigger_activities" field.
func TriggerActivitiesGTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGTE(FieldTriggerActivities, v))
}

// TriggerActivitiesLT applies the LT predicate on the "trigger_activities" field.
func TriggerActivitiesLT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLT(FieldTriggerActivities, v))
}

// TriggerActivitiesLTE applies the LTE predicate on the "trigger_activities" field.
func TriggerActivitiesLTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLTE(FieldTriggerActivities, v))
}

// TriggerActivitiesContains applies the Contains predicate on the "trigger_activities" field.
func TriggerActivitiesContains(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContains(FieldTriggerActivities, v))
}

// TriggerActivitiesHasPrefix applies the HasPrefix predicate on the "trigger_activities" field.
func TriggerActivitiesHasPrefix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasPrefix(FieldTriggerActivities, v))
}

// TriggerActivitiesHasSuffix applies the HasSuffix predicate on the "trigger_activities" field.
func TriggerActivitiesHasSuffix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasSuffix(FieldTriggerActivities, v))
}

// TriggerActivitiesEqualFold applies the EqualFold predicate on the "trigger_activities" field.
func TriggerActivitiesEqualFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEqualFold(FieldTriggerActivities, v))
}

// TriggerActivitiesContainsFold applies the ContainsFold predicate on the "trigger_activities" field.
func TriggerActivitiesContainsFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContainsFold(FieldTriggerActivities, v))
}

// GroveIDEQ applies the EQ predicate on the "grove_id" field.
func GroveIDEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldGroveID, v))
}

// GroveIDNEQ applies the NEQ predicate on the "grove_id" field.
func GroveIDNEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNEQ(FieldGroveID, v))
}

// GroveIDIn applies the In predicate on the "grove_id" field.
func GroveIDIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldIn(FieldGroveID, vs...))
}

// GroveIDNotIn applies the NotIn predicate on the "grove_id" field.
func GroveIDNotIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNotIn(FieldGroveID, vs...))
}

// GroveIDGT applies the GT predicate on the "grove_id" field.
func GroveIDGT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGT(FieldGroveID, v))
}

// GroveIDGTE applies the GTE predicate on the "grove_id" field.
func GroveIDGTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGTE(FieldGroveID, v))
}

// GroveIDLT applies the LT predicate on the "grove_id" field.
func GroveIDLT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLT(FieldGroveID, v))
}

// GroveIDLTE applies the LTE predicate on the "grove_id" field.
func GroveIDLTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLTE(FieldGroveID, v))
}

// GroveIDContains applies the Contains predicate on the "grove_id" field.
func GroveIDContains(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContains(FieldGroveID, v))
}

// GroveIDHasPrefix applies the HasPrefix predicate on the "grove_id" field.
func GroveIDHasPrefix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasPrefix(FieldGroveID, v))
}

// GroveIDHasSuffix applies the HasSuffix predicate on the "grove_id" field.
func GroveIDHasSuffix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasSuffix(FieldGroveID, v))
}

// GroveIDEqualFold applies the EqualFold predicate on the "grove_id" field.
func GroveIDEqualFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEqualFold(FieldGroveID, v))
}

// GroveIDContainsFold applies the ContainsFold predicate on the "grove_id" field.
func GroveIDContainsFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContainsFold(FieldGroveID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.FieldContainsFold(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionTemplate) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionTemplate) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionTemplate) predicate.SubscriptionTemplate {
	return predicate.SubscriptionTemplate(sql.NotPredicates(p))
}
