{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scion.fullname" . }}
  labels:
    {{- include "scion.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scion.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scion.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scion.fullname" . }}
  namespace: {{ include "scion.agentNamespace" . }}
  labels:
    {{- include "scion.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scion.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scion.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
