# Scion Hub Settings
# Generated by deploy.sh — do not edit directly.
settings_version: "1"
server:
  hub:
    name: "__HUB_NAME__"
  storage:
    local_path: /home/scion/.scion/workspace-storage
  secrets:
    backend: local
  auth:
    mode: dev
  listen_port: 8080
