// Code generated by ent, DO NOT EDIT.

package envvar

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldKey, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldValue, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldScope, v))
}

// ScopeID applies equality check predicate on the "scope_id" field. It's identical to ScopeIDEQ.
func ScopeID(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldScopeID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldDescription, v))
}

// Sensitive applies equality check predicate on the "sensitive" field. It's identical to SensitiveEQ.
func Sensitive(v bool) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldSensitive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldCreatedBy, v))
}

// InjectionMode applies equality check predicate on the "injection_mode" field. It's identical to InjectionModeEQ.
func InjectionMode(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldInjectionMode, v))
}

// Secret applies equality check predicate on the "secret" field. It's identical to SecretEQ.
func Secret(v bool) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldSecret, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldKey, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldValue, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldScope, v))
}

// ScopeIDEQ applies the EQ predicate on the "scope_id" field.
func ScopeIDEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldScopeID, v))
}

// ScopeIDNEQ applies the NEQ predicate on the "scope_id" field.
func ScopeIDNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldScopeID, v))
}

// ScopeIDIn applies the In predicate on the "scope_id" field.
func ScopeIDIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldScopeID, vs...))
}

// ScopeIDNotIn applies the NotIn predicate on the "scope_id" field.
func ScopeIDNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldScopeID, vs...))
}

// ScopeIDGT applies the GT predicate on the "scope_id" field.
func ScopeIDGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldScopeID, v))
}

// ScopeIDGTE applies the GTE predicate on the "scope_id" field.
func ScopeIDGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldScopeID, v))
}

// ScopeIDLT applies the LT predicate on the "scope_id" field.
func ScopeIDLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldScopeID, v))
}

// ScopeIDLTE applies the LTE predicate on the "scope_id" field.
func ScopeIDLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldScopeID, v))
}

// ScopeIDContains applies the Contains predicate on the "scope_id" field.
func ScopeIDContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldScopeID, v))
}

// ScopeIDHasPrefix applies the HasPrefix predicate on the "scope_id" field.
func ScopeIDHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldScopeID, v))
}

// ScopeIDHasSuffix applies the HasSuffix predicate on the "scope_id" field.
func ScopeIDHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldScopeID, v))
}

// ScopeIDEqualFold applies the EqualFold predicate on the "scope_id" field.
func ScopeIDEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldScopeID, v))
}

// ScopeIDContainsFold applies the ContainsFold predicate on the "scope_id" field.
func ScopeIDContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldScopeID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldDescription, v))
}

// SensitiveEQ applies the EQ predicate on the "sensitive" field.
func SensitiveEQ(v bool) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldSensitive, v))
}

// SensitiveNEQ applies the NEQ predicate on the "sensitive" field.
func SensitiveNEQ(v bool) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldSensitive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldCreatedBy, v))
}

// InjectionModeEQ applies the EQ predicate on the "injection_mode" field.
func InjectionModeEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldInjectionMode, v))
}

// InjectionModeNEQ applies the NEQ predicate on the "injection_mode" field.
func InjectionModeNEQ(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldInjectionMode, v))
}

// InjectionModeIn applies the In predicate on the "injection_mode" field.
func InjectionModeIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldIn(FieldInjectionMode, vs...))
}

// InjectionModeNotIn applies the NotIn predicate on the "injection_mode" field.
func InjectionModeNotIn(vs ...string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNotIn(FieldInjectionMode, vs...))
}

// InjectionModeGT applies the GT predicate on the "injection_mode" field.
func InjectionModeGT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGT(FieldInjectionMode, v))
}

// InjectionModeGTE applies the GTE predicate on the "injection_mode" field.
func InjectionModeGTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldGTE(FieldInjectionMode, v))
}

// InjectionModeLT applies the LT predicate on the "injection_mode" field.
func InjectionModeLT(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLT(FieldInjectionMode, v))
}

// InjectionModeLTE applies the LTE predicate on the "injection_mode" field.
func InjectionModeLTE(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldLTE(FieldInjectionMode, v))
}

// InjectionModeContains applies the Contains predicate on the "injection_mode" field.
func InjectionModeContains(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContains(FieldInjectionMode, v))
}

// InjectionModeHasPrefix applies the HasPrefix predicate on the "injection_mode" field.
func InjectionModeHasPrefix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasPrefix(FieldInjectionMode, v))
}

// InjectionModeHasSuffix applies the HasSuffix predicate on the "injection_mode" field.
func InjectionModeHasSuffix(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldHasSuffix(FieldInjectionMode, v))
}

// InjectionModeEqualFold applies the EqualFold predicate on the "injection_mode" field.
func InjectionModeEqualFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEqualFold(FieldInjectionMode, v))
}

// InjectionModeContainsFold applies the ContainsFold predicate on the "injection_mode" field.
func InjectionModeContainsFold(v string) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldContainsFold(FieldInjectionMode, v))
}

// SecretEQ applies the EQ predicate on the "secret" field.
func SecretEQ(v bool) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldEQ(FieldSecret, v))
}

// SecretNEQ applies the NEQ predicate on the "secret" field.
func SecretNEQ(v bool) predicate.EnvVar {
	return predicate.EnvVar(sql.FieldNEQ(FieldSecret, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnvVar) predicate.EnvVar {
	return predicate.EnvVar(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnvVar) predicate.EnvVar {
	return predicate.EnvVar(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnvVar) predicate.EnvVar {
	return predicate.EnvVar(sql.NotPredicates(p))
}
