// Code generated by ent, DO NOT EDIT.

package notificationsubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the notificationsubscription type in the database.
	Label = "notification_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldSubscriberType holds the string denoting the subscriber_type field in the database.
	FieldSubscriberType = "subscriber_type"
	// FieldSubscriberID holds the string denoting the subscriber_id field in the database.
	FieldSubscriberID = "subscriber_id"
	// FieldGroveID holds the string denoting the grove_id field in the database.
	FieldGroveID = "grove_id"
	// FieldTriggerActivities holds the string denoting the trigger_activities field in the database.
	FieldTriggerActivities = "trigger_activities"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// Table holds the table name of the notificationsubscription in the database.
	Table = "notification_subscriptions"
)

// Columns holds all SQL columns for notificationsubscription fields.
var Columns = []string{
	FieldID,
	FieldScope,
	FieldAgentID,
	FieldSubscriberType,
	FieldSubscriberID,
	FieldGroveID,
	FieldTriggerActivities,
	FieldCreatedAt,
	FieldCreatedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScope holds the default value on creation for the "scope" field.
	DefaultScope string
	// DefaultSubscriberType holds the default value on creation for the "subscriber_type" field.
	DefaultSubscriberType string
	// SubscriberIDValidator is a validator for the "subscriber_id" field. It is called by the builders before save.
	SubscriberIDValidator func(string) error
	// GroveIDValidator is a validator for the "grove_id" field. It is called by the builders before save.
	GroveIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
)

// OrderOption defines the ordering options for the NotificationSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// BySubscriberType orders the results by the subscriber_type field.
func BySubscriberType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriberType, opts...).ToFunc()
}

// BySubscriberID orders the results by the subscriber_id field.
func BySubscriberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriberID, opts...).ToFunc()
}

// ByGroveID orders the results by the grove_id field.
func ByGroveID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroveID, opts...).ToFunc()
}

// ByTriggerActivities orders the results by the trigger_activities field.
func ByTriggerActivities(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerActivities, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}
