// Code generated by ent, DO NOT EDIT.

package notificationsubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldID, id))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldScope, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldAgentID, v))
}

// SubscriberType applies equality check predicate on the "subscriber_type" field. It's identical to SubscriberTypeEQ.
func SubscriberType(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldSubscriberType, v))
}

// SubscriberID applies equality check predicate on the "subscriber_id" field. It's identical to SubscriberIDEQ.
func SubscriberID(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldSubscriberID, v))
}

// GroveID applies equality check predicate on the "grove_id" field. It's identical to GroveIDEQ.
func GroveID(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldGroveID, v))
}

// TriggerActivities applies equality check predicate on the "trigger_activities" field. It's identical to TriggerActivitiesEQ.
func TriggerActivities(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldTriggerActivities, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldCreatedBy, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldScope, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotNull(FieldAgentID))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldAgentID, v))
}

// SubscriberTypeEQ applies the EQ predicate on the "subscriber_type" field.
func SubscriberTypeEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldSubscriberType, v))
}

// SubscriberTypeNEQ applies the NEQ predicate on the "subscriber_type" field.
func SubscriberTypeNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldSubscriberType, v))
}

// SubscriberTypeIn applies the In predicate on the "subscriber_type" field.
func SubscriberTypeIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldSubscriberType, vs...))
}

// SubscriberTypeNotIn applies the NotIn predicate on the "subscriber_type" field.
func SubscriberTypeNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldSubscriberType, vs...))
}

// SubscriberTypeGT applies the GT predicate on the "subscriber_type" field.
func SubscriberTypeGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldSubscriberType, v))
}

// SubscriberTypeGTE applies the GTE predicate on the "subscriber_type" field.
func SubscriberTypeGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldSubscriberType, v))
}

// SubscriberTypeLT applies the LT predicate on the "subscriber_type" field.
func SubscriberTypeLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldSubscriberType, v))
}

// SubscriberTypeLTE applies the LTE predicate on the "subscriber_type" field.
func SubscriberTypeLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldSubscriberType, v))
}

// SubscriberTypeContains applies the Contains predicate on the "subscriber_type" field.
func SubscriberTypeContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldSubscriberType, v))
}

// SubscriberTypeHasPrefix applies the HasPrefix predicate on the "subscriber_type" field.
func SubscriberTypeHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldSubscriberType, v))
}

// SubscriberTypeHasSuffix applies the HasSuffix predicate on the "subscriber_type" field.
func SubscriberTypeHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldSubscriberType, v))
}

// SubscriberTypeEqualFold applies the EqualFold predicate on the "subscriber_type" field.
func SubscriberTypeEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldSubscriberType, v))
}

// SubscriberTypeContainsFold applies the ContainsFold predicate on the "subscriber_type" field.
func SubscriberTypeContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldSubscriberType, v))
}

// SubscriberIDEQ applies the EQ predicate on the "subscriber_id" field.
func SubscriberIDEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldSubscriberID, v))
}

// SubscriberIDNEQ applies the NEQ predicate on the "subscriber_id" field.
func SubscriberIDNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldSubscriberID, v))
}

// SubscriberIDIn applies the In predicate on the "subscriber_id" field.
func SubscriberIDIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldSubscriberID, vs...))
}

// SubscriberIDNotIn applies the NotIn predicate on the "subscriber_id" field.
func SubscriberIDNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldSubscriberID, vs...))
}

// SubscriberIDGT applies the GT predicate on the "subscriber_id" field.
func SubscriberIDGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldSubscriberID, v))
}

// SubscriberIDGTE applies the GTE predicate on the "subscriber_id" field.
func SubscriberIDGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldSubscriberID, v))
}

// SubscriberIDLT applies the LT predicate on the "subscriber_id" field.
func SubscriberIDLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldSubscriberID, v))
}

// SubscriberIDLTE applies the LTE predicate on the "subscriber_id" field.
func SubscriberIDLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldSubscriberID, v))
}

// SubscriberIDContains applies the Contains predicate on the "subscriber_id" field.
func SubscriberIDContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldSubscriberID, v))
}

// SubscriberIDHasPrefix applies the HasPrefix predicate on the "subscriber_id" field.
func SubscriberIDHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldSubscriberID, v))
}

// SubscriberIDHasSuffix applies the HasSuffix predicate on the "subscriber_id" field.
func SubscriberIDHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldSubscriberID, v))
}

// SubscriberIDEqualFold applies the EqualFold predicate on the "subscriber_id" field.
func SubscriberIDEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldSubscriberID, v))
}

// SubscriberIDContainsFold applies the ContainsFold predicate on the "subscriber_id" field.
func SubscriberIDContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldSubscriberID, v))
}

// GroveIDEQ applies the EQ predicate on the "grove_id" field.
func GroveIDEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldGroveID, v))
}

// GroveIDNEQ applies the NEQ predicate on the "grove_id" field.
func GroveIDNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldGroveID, v))
}

// GroveIDIn applies the In predicate on the "grove_id" field.
func GroveIDIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldGroveID, vs...))
}

// GroveIDNotIn applies the NotIn predicate on the "grove_id" field.
func GroveIDNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldGroveID, vs...))
}

// GroveIDGT applies the GT predicate on the "grove_id" field.
func GroveIDGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldGroveID, v))
}

// GroveIDGTE applies the GTE predicate on the "grove_id" field.
func GroveIDGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldGroveID, v))
}

// GroveIDLT applies the LT predicate on the "grove_id" field.
func GroveIDLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldGroveID, v))
}

// GroveIDLTE applies the LTE predicate on the "grove_id" field.
func GroveIDLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldGroveID, v))
}

// GroveIDContains applies the Contains predicate on the "grove_id" field.
func GroveIDContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldGroveID, v))
}

// GroveIDHasPrefix applies the HasPrefix predicate on the "grove_id" field.
func GroveIDHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldGroveID, v))
}

// GroveIDHasSuffix applies the HasSuffix predicate on the "grove_id" field.
func GroveIDHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldGroveID, v))
}

// GroveIDEqualFold applies the EqualFold predicate on the "grove_id" field.
func GroveIDEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldGroveID, v))
}

// GroveIDContainsFold applies the ContainsFold predicate on the "grove_id" field.
func GroveIDContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldGroveID, v))
}

// TriggerActivitiesEQ applies the EQ predicate on the "trigger_activities" field.
func TriggerActivitiesEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldTriggerActivities, v))
}

// TriggerActivitiesNEQ applies the NEQ predicate on the "trigger_activities" field.
func TriggerActivitiesNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldTriggerActivities, v))
}

// TriggerActivitiesIn applies the In predicate on the "trigger_activities" field.
func TriggerActivitiesIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldTriggerActivities, vs...))
}

// TriggerActivitiesNotIn applies the NotIn predicate on the "trigger_activities" field.
func TriggerActivitiesNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldTriggerActivities, vs...))
}

// TriggerActivitiesGT applies the GT predicate on the "trigger_activities" field.
func TriggerActivitiesGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldTriggerActivities, v))
}

// TriggerActivitiesGTE applies the GTE predicate on the "trigger_activities" field.
func TriggerActivitiesGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldTriggerActivities, v))
}

// TriggerActivitiesLT applies the LT predicate on the "trigger_activities" field.
func TriggerActivitiesLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldTriggerActivities, v))
}

// TriggerActivitiesLTE applies the LTE predicate on the "trigger_activities" field.
func TriggerActivitiesLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldTriggerActivities, v))
}

// TriggerActivitiesContains applies the Contains predicate on the "trigger_activities" field.
func TriggerActivitiesContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldTriggerActivities, v))
}

// TriggerActivitiesHasPrefix applies the HasPrefix predicate on the "trigger_activities" field.
func TriggerActivitiesHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldTriggerActivities, v))
}

// TriggerActivitiesHasSuffix applies the HasSuffix predicate on the "trigger_activities" field.
func TriggerActivitiesHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldTriggerActivities, v))
}

// TriggerActivitiesEqualFold applies the EqualFold predicate on the "trigger_activities" field.
func TriggerActivitiesEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldTriggerActivities, v))
}

// TriggerActivitiesContainsFold applies the ContainsFold predicate on the "trigger_activities" field.
func TriggerActivitiesContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldTriggerActivities, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.FieldContainsFold(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationSubscription) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationSubscription) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationSubscription) predicate.NotificationSubscription {
	return predicate.NotificationSubscription(sql.NotPredicates(p))
}
