// Code generated by ent, DO NOT EDIT.

package grovecontributor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldID, id))
}

// GroveID applies equality check predicate on the "grove_id" field. It's identical to GroveIDEQ.
func GroveID(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldGroveID, v))
}

// BrokerID applies equality check predicate on the "broker_id" field. It's identical to BrokerIDEQ.
func BrokerID(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldBrokerID, v))
}

// BrokerName applies equality check predicate on the "broker_name" field. It's identical to BrokerNameEQ.
func BrokerName(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldBrokerName, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldMode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldStatus, v))
}

// Profiles applies equality check predicate on the "profiles" field. It's identical to ProfilesEQ.
func Profiles(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldProfiles, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLastSeen, v))
}

// LocalPath applies equality check predicate on the "local_path" field. It's identical to LocalPathEQ.
func LocalPath(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLocalPath, v))
}

// LinkedBy applies equality check predicate on the "linked_by" field. It's identical to LinkedByEQ.
func LinkedBy(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLinkedBy, v))
}

// LinkedAt applies equality check predicate on the "linked_at" field. It's identical to LinkedAtEQ.
func LinkedAt(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLinkedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldCreatedAt, v))
}

// GroveIDEQ applies the EQ predicate on the "grove_id" field.
func GroveIDEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldGroveID, v))
}

// GroveIDNEQ applies the NEQ predicate on the "grove_id" field.
func GroveIDNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldGroveID, v))
}

// GroveIDIn applies the In predicate on the "grove_id" field.
func GroveIDIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldGroveID, vs...))
}

// GroveIDNotIn applies the NotIn predicate on the "grove_id" field.
func GroveIDNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldGroveID, vs...))
}

// GroveIDGT applies the GT predicate on the "grove_id" field.
func GroveIDGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldGroveID, v))
}

// GroveIDGTE applies the GTE predicate on the "grove_id" field.
func GroveIDGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldGroveID, v))
}

// GroveIDLT applies the LT predicate on the "grove_id" field.
func GroveIDLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldGroveID, v))
}

// GroveIDLTE applies the LTE predicate on the "grove_id" field.
func GroveIDLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldGroveID, v))
}

// GroveIDContains applies the Contains predicate on the "grove_id" field.
func GroveIDContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldGroveID, v))
}

// GroveIDHasPrefix applies the HasPrefix predicate on the "grove_id" field.
func GroveIDHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldGroveID, v))
}

// GroveIDHasSuffix applies the HasSuffix predicate on the "grove_id" field.
func GroveIDHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldGroveID, v))
}

// GroveIDEqualFold applies the EqualFold predicate on the "grove_id" field.
func GroveIDEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldGroveID, v))
}

// GroveIDContainsFold applies the ContainsFold predicate on the "grove_id" field.
func GroveIDContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldGroveID, v))
}

// BrokerIDEQ applies the EQ predicate on the "broker_id" field.
func BrokerIDEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldBrokerID, v))
}

// BrokerIDNEQ applies the NEQ predicate on the "broker_id" field.
func BrokerIDNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldBrokerID, v))
}

// BrokerIDIn applies the In predicate on the "broker_id" field.
func BrokerIDIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldBrokerID, vs...))
}

// BrokerIDNotIn applies the NotIn predicate on the "broker_id" field.
func BrokerIDNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldBrokerID, vs...))
}

// BrokerIDGT applies the GT predicate on the "broker_id" field.
func BrokerIDGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldBrokerID, v))
}

// BrokerIDGTE applies the GTE predicate on the "broker_id" field.
func BrokerIDGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldBrokerID, v))
}

// BrokerIDLT applies the LT predicate on the "broker_id" field.
func BrokerIDLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldBrokerID, v))
}

// BrokerIDLTE applies the LTE predicate on the "broker_id" field.
func BrokerIDLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldBrokerID, v))
}

// BrokerIDContains applies the Contains predicate on the "broker_id" field.
func BrokerIDContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldBrokerID, v))
}

// BrokerIDHasPrefix applies the HasPrefix predicate on the "broker_id" field.
func BrokerIDHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldBrokerID, v))
}

// BrokerIDHasSuffix applies the HasSuffix predicate on the "broker_id" field.
func BrokerIDHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldBrokerID, v))
}

// BrokerIDEqualFold applies the EqualFold predicate on the "broker_id" field.
func BrokerIDEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldBrokerID, v))
}

// BrokerIDContainsFold applies the ContainsFold predicate on the "broker_id" field.
func BrokerIDContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldBrokerID, v))
}

// BrokerNameEQ applies the EQ predicate on the "broker_name" field.
func BrokerNameEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldBrokerName, v))
}

// BrokerNameNEQ applies the NEQ predicate on the "broker_name" field.
func BrokerNameNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldBrokerName, v))
}

// BrokerNameIn applies the In predicate on the "broker_name" field.
func BrokerNameIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldBrokerName, vs...))
}

// BrokerNameNotIn applies the NotIn predicate on the "broker_name" field.
func BrokerNameNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldBrokerName, vs...))
}

// BrokerNameGT applies the GT predicate on the "broker_name" field.
func BrokerNameGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldBrokerName, v))
}

// BrokerNameGTE applies the GTE predicate on the "broker_name" field.
func BrokerNameGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldBrokerName, v))
}

// BrokerNameLT applies the LT predicate on the "broker_name" field.
func BrokerNameLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldBrokerName, v))
}

// BrokerNameLTE applies the LTE predicate on the "broker_name" field.
func BrokerNameLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldBrokerName, v))
}

// BrokerNameContains applies the Contains predicate on the "broker_name" field.
func BrokerNameContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldBrokerName, v))
}

// BrokerNameHasPrefix applies the HasPrefix predicate on the "broker_name" field.
func BrokerNameHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldBrokerName, v))
}

// BrokerNameHasSuffix applies the HasSuffix predicate on the "broker_name" field.
func BrokerNameHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldBrokerName, v))
}

// BrokerNameEqualFold applies the EqualFold predicate on the "broker_name" field.
func BrokerNameEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldBrokerName, v))
}

// BrokerNameContainsFold applies the ContainsFold predicate on the "broker_name" field.
func BrokerNameContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldBrokerName, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldMode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldStatus, v))
}

// ProfilesEQ applies the EQ predicate on the "profiles" field.
func ProfilesEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldProfiles, v))
}

// ProfilesNEQ applies the NEQ predicate on the "profiles" field.
func ProfilesNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldProfiles, v))
}

// ProfilesIn applies the In predicate on the "profiles" field.
func ProfilesIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldProfiles, vs...))
}

// ProfilesNotIn applies the NotIn predicate on the "profiles" field.
func ProfilesNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldProfiles, vs...))
}

// ProfilesGT applies the GT predicate on the "profiles" field.
func ProfilesGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldProfiles, v))
}

// ProfilesGTE applies the GTE predicate on the "profiles" field.
func ProfilesGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldProfiles, v))
}

// ProfilesLT applies the LT predicate on the "profiles" field.
func ProfilesLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldProfiles, v))
}

// ProfilesLTE applies the LTE predicate on the "profiles" field.
func ProfilesLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldProfiles, v))
}

// ProfilesContains applies the Contains predicate on the "profiles" field.
func ProfilesContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldProfiles, v))
}

// ProfilesHasPrefix applies the HasPrefix predicate on the "profiles" field.
func ProfilesHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldProfiles, v))
}

// ProfilesHasSuffix applies the HasSuffix predicate on the "profiles" field.
func ProfilesHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldProfiles, v))
}

// ProfilesIsNil applies the IsNil predicate on the "profiles" field.
func ProfilesIsNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIsNull(FieldProfiles))
}

// ProfilesNotNil applies the NotNil predicate on the "profiles" field.
func ProfilesNotNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotNull(FieldProfiles))
}

// ProfilesEqualFold applies the EqualFold predicate on the "profiles" field.
func ProfilesEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldProfiles, v))
}

// ProfilesContainsFold applies the ContainsFold predicate on the "profiles" field.
func ProfilesContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldProfiles, v))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldLastSeen, v))
}

// LastSeenIsNil applies the IsNil predicate on the "last_seen" field.
func LastSeenIsNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIsNull(FieldLastSeen))
}

// LastSeenNotNil applies the NotNil predicate on the "last_seen" field.
func LastSeenNotNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotNull(FieldLastSeen))
}

// LocalPathEQ applies the EQ predicate on the "local_path" field.
func LocalPathEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLocalPath, v))
}

// LocalPathNEQ applies the NEQ predicate on the "local_path" field.
func LocalPathNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldLocalPath, v))
}

// LocalPathIn applies the In predicate on the "local_path" field.
func LocalPathIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldLocalPath, vs...))
}

// LocalPathNotIn applies the NotIn predicate on the "local_path" field.
func LocalPathNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldLocalPath, vs...))
}

// LocalPathGT applies the GT predicate on the "local_path" field.
func LocalPathGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldLocalPath, v))
}

// LocalPathGTE applies the GTE predicate on the "local_path" field.
func LocalPathGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldLocalPath, v))
}

// LocalPathLT applies the LT predicate on the "local_path" field.
func LocalPathLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldLocalPath, v))
}

// LocalPathLTE applies the LTE predicate on the "local_path" field.
func LocalPathLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldLocalPath, v))
}

// LocalPathContains applies the Contains predicate on the "local_path" field.
func LocalPathContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldLocalPath, v))
}

// LocalPathHasPrefix applies the HasPrefix predicate on the "local_path" field.
func LocalPathHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldLocalPath, v))
}

// LocalPathHasSuffix applies the HasSuffix predicate on the "local_path" field.
func LocalPathHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldLocalPath, v))
}

// LocalPathIsNil applies the IsNil predicate on the "local_path" field.
func LocalPathIsNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIsNull(FieldLocalPath))
}

// LocalPathNotNil applies the NotNil predicate on the "local_path" field.
func LocalPathNotNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotNull(FieldLocalPath))
}

// LocalPathEqualFold applies the EqualFold predicate on the "local_path" field.
func LocalPathEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldLocalPath, v))
}

// LocalPathContainsFold applies the ContainsFold predicate on the "local_path" field.
func LocalPathContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldLocalPath, v))
}

// LinkedByEQ applies the EQ predicate on the "linked_by" field.
func LinkedByEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLinkedBy, v))
}

// LinkedByNEQ applies the NEQ predicate on the "linked_by" field.
func LinkedByNEQ(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldLinkedBy, v))
}

// LinkedByIn applies the In predicate on the "linked_by" field.
func LinkedByIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldLinkedBy, vs...))
}

// LinkedByNotIn applies the NotIn predicate on the "linked_by" field.
func LinkedByNotIn(vs ...string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldLinkedBy, vs...))
}

// LinkedByGT applies the GT predicate on the "linked_by" field.
func LinkedByGT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldLinkedBy, v))
}

// LinkedByGTE applies the GTE predicate on the "linked_by" field.
func LinkedByGTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldLinkedBy, v))
}

// LinkedByLT applies the LT predicate on the "linked_by" field.
func LinkedByLT(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldLinkedBy, v))
}

// LinkedByLTE applies the LTE predicate on the "linked_by" field.
func LinkedByLTE(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldLinkedBy, v))
}

// LinkedByContains applies the Contains predicate on the "linked_by" field.
func LinkedByContains(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContains(FieldLinkedBy, v))
}

// LinkedByHasPrefix applies the HasPrefix predicate on the "linked_by" field.
func LinkedByHasPrefix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasPrefix(FieldLinkedBy, v))
}

// LinkedByHasSuffix applies the HasSuffix predicate on the "linked_by" field.
func LinkedByHasSuffix(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldHasSuffix(FieldLinkedBy, v))
}

// LinkedByIsNil applies the IsNil predicate on the "linked_by" field.
func LinkedByIsNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIsNull(FieldLinkedBy))
}

// LinkedByNotNil applies the NotNil predicate on the "linked_by" field.
func LinkedByNotNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotNull(FieldLinkedBy))
}

// LinkedByEqualFold applies the EqualFold predicate on the "linked_by" field.
func LinkedByEqualFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEqualFold(FieldLinkedBy, v))
}

// LinkedByContainsFold applies the ContainsFold predicate on the "linked_by" field.
func LinkedByContainsFold(v string) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldContainsFold(FieldLinkedBy, v))
}

// LinkedAtEQ applies the EQ predicate on the "linked_at" field.
func LinkedAtEQ(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldLinkedAt, v))
}

// LinkedAtNEQ applies the NEQ predicate on the "linked_at" field.
func LinkedAtNEQ(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldLinkedAt, v))
}

// LinkedAtIn applies the In predicate on the "linked_at" field.
func LinkedAtIn(vs ...time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldLinkedAt, vs...))
}

// LinkedAtNotIn applies the NotIn predicate on the "linked_at" field.
func LinkedAtNotIn(vs ...time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldLinkedAt, vs...))
}

// LinkedAtGT applies the GT predicate on the "linked_at" field.
func LinkedAtGT(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldLinkedAt, v))
}

// LinkedAtGTE applies the GTE predicate on the "linked_at" field.
func LinkedAtGTE(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldLinkedAt, v))
}

// LinkedAtLT applies the LT predicate on the "linked_at" field.
func LinkedAtLT(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldLinkedAt, v))
}

// LinkedAtLTE applies the LTE predicate on the "linked_at" field.
func LinkedAtLTE(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldLinkedAt, v))
}

// LinkedAtIsNil applies the IsNil predicate on the "linked_at" field.
func LinkedAtIsNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIsNull(FieldLinkedAt))
}

// LinkedAtNotNil applies the NotNil predicate on the "linked_at" field.
func LinkedAtNotNil() predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotNull(FieldLinkedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroveContributor {
	return predicate.GroveContributor(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroveContributor) predicate.GroveContributor {
	return predicate.GroveContributor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroveContributor) predicate.GroveContributor {
	return predicate.GroveContributor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroveContributor) predicate.GroveContributor {
	return predicate.GroveContributor(sql.NotPredicates(p))
}
