// Code generated by ent, DO NOT EDIT.

package githubinstallation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldID, id))
}

// AccountLogin applies equality check predicate on the "account_login" field. It's identical to AccountLoginEQ.
func AccountLogin(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldAccountLogin, v))
}

// AccountType applies equality check predicate on the "account_type" field. It's identical to AccountTypeEQ.
func AccountType(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldAccountType, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldAppID, v))
}

// Repositories applies equality check predicate on the "repositories" field. It's identical to RepositoriesEQ.
func Repositories(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldRepositories, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountLoginEQ applies the EQ predicate on the "account_login" field.
func AccountLoginEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldAccountLogin, v))
}

// AccountLoginNEQ applies the NEQ predicate on the "account_login" field.
func AccountLoginNEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldAccountLogin, v))
}

// AccountLoginIn applies the In predicate on the "account_login" field.
func AccountLoginIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldAccountLogin, vs...))
}

// AccountLoginNotIn applies the NotIn predicate on the "account_login" field.
func AccountLoginNotIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldAccountLogin, vs...))
}

// AccountLoginGT applies the GT predicate on the "account_login" field.
func AccountLoginGT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldAccountLogin, v))
}

// AccountLoginGTE applies the GTE predicate on the "account_login" field.
func AccountLoginGTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldAccountLogin, v))
}

// AccountLoginLT applies the LT predicate on the "account_login" field.
func AccountLoginLT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldAccountLogin, v))
}

// AccountLoginLTE applies the LTE predicate on the "account_login" field.
func AccountLoginLTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldAccountLogin, v))
}

// AccountLoginContains applies the Contains predicate on the "account_login" field.
func AccountLoginContains(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContains(FieldAccountLogin, v))
}

// AccountLoginHasPrefix applies the HasPrefix predicate on the "account_login" field.
func AccountLoginHasPrefix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasPrefix(FieldAccountLogin, v))
}

// AccountLoginHasSuffix applies the HasSuffix predicate on the "account_login" field.
func AccountLoginHasSuffix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasSuffix(FieldAccountLogin, v))
}

// AccountLoginEqualFold applies the EqualFold predicate on the "account_login" field.
func AccountLoginEqualFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEqualFold(FieldAccountLogin, v))
}

// AccountLoginContainsFold applies the ContainsFold predicate on the "account_login" field.
func AccountLoginContainsFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContainsFold(FieldAccountLogin, v))
}

// AccountTypeEQ applies the EQ predicate on the "account_type" field.
func AccountTypeEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldAccountType, v))
}

// AccountTypeNEQ applies the NEQ predicate on the "account_type" field.
func AccountTypeNEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldAccountType, v))
}

// AccountTypeIn applies the In predicate on the "account_type" field.
func AccountTypeIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldAccountType, vs...))
}

// AccountTypeNotIn applies the NotIn predicate on the "account_type" field.
func AccountTypeNotIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldAccountType, vs...))
}

// AccountTypeGT applies the GT predicate on the "account_type" field.
func AccountTypeGT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldAccountType, v))
}

// AccountTypeGTE applies the GTE predicate on the "account_type" field.
func AccountTypeGTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldAccountType, v))
}

// AccountTypeLT applies the LT predicate on the "account_type" field.
func AccountTypeLT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldAccountType, v))
}

// AccountTypeLTE applies the LTE predicate on the "account_type" field.
func AccountTypeLTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldAccountType, v))
}

// AccountTypeContains applies the Contains predicate on the "account_type" field.
func AccountTypeContains(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContains(FieldAccountType, v))
}

// AccountTypeHasPrefix applies the HasPrefix predicate on the "account_type" field.
func AccountTypeHasPrefix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasPrefix(FieldAccountType, v))
}

// AccountTypeHasSuffix applies the HasSuffix predicate on the "account_type" field.
func AccountTypeHasSuffix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasSuffix(FieldAccountType, v))
}

// AccountTypeEqualFold applies the EqualFold predicate on the "account_type" field.
func AccountTypeEqualFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEqualFold(FieldAccountType, v))
}

// AccountTypeContainsFold applies the ContainsFold predicate on the "account_type" field.
func AccountTypeContainsFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContainsFold(FieldAccountType, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v int64) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldAppID, v))
}

// RepositoriesEQ applies the EQ predicate on the "repositories" field.
func RepositoriesEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldRepositories, v))
}

// RepositoriesNEQ applies the NEQ predicate on the "repositories" field.
func RepositoriesNEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldRepositories, v))
}

// RepositoriesIn applies the In predicate on the "repositories" field.
func RepositoriesIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldRepositories, vs...))
}

// RepositoriesNotIn applies the NotIn predicate on the "repositories" field.
func RepositoriesNotIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldRepositories, vs...))
}

// RepositoriesGT applies the GT predicate on the "repositories" field.
func RepositoriesGT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldRepositories, v))
}

// RepositoriesGTE applies the GTE predicate on the "repositories" field.
func RepositoriesGTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldRepositories, v))
}

// RepositoriesLT applies the LT predicate on the "repositories" field.
func RepositoriesLT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldRepositories, v))
}

// RepositoriesLTE applies the LTE predicate on the "repositories" field.
func RepositoriesLTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldRepositories, v))
}

// RepositoriesContains applies the Contains predicate on the "repositories" field.
func RepositoriesContains(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContains(FieldRepositories, v))
}

// RepositoriesHasPrefix applies the HasPrefix predicate on the "repositories" field.
func RepositoriesHasPrefix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasPrefix(FieldRepositories, v))
}

// RepositoriesHasSuffix applies the HasSuffix predicate on the "repositories" field.
func RepositoriesHasSuffix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasSuffix(FieldRepositories, v))
}

// RepositoriesEqualFold applies the EqualFold predicate on the "repositories" field.
func RepositoriesEqualFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEqualFold(FieldRepositories, v))
}

// RepositoriesContainsFold applies the ContainsFold predicate on the "repositories" field.
func RepositoriesContainsFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContainsFold(FieldRepositories, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GitHubInstallation) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GitHubInstallation) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GitHubInstallation) predicate.GitHubInstallation {
	return predicate.GitHubInstallation(sql.NotPredicates(p))
}
