// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentserviceaccountassignment"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// AgentServiceAccountAssignmentDelete is the builder for deleting a AgentServiceAccountAssignment entity.
type AgentServiceAccountAssignmentDelete struct {
	config
	hooks    []Hook
	mutation *AgentServiceAccountAssignmentMutation
}

// Where appends a list predicates to the AgentServiceAccountAssignmentDelete builder.
func (_d *AgentServiceAccountAssignmentDelete) Where(ps ...predicate.AgentServiceAccountAssignment) *AgentServiceAccountAssignmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentServiceAccountAssignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentServiceAccountAssignmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentServiceAccountAssignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentserviceaccountassignment.Table, sqlgraph.NewFieldSpec(agentserviceaccountassignment.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentServiceAccountAssignmentDeleteOne is the builder for deleting a single AgentServiceAccountAssignment entity.
type AgentServiceAccountAssignmentDeleteOne struct {
	_d *AgentServiceAccountAssignmentDelete
}

// Where appends a list predicates to the AgentServiceAccountAssignmentDelete builder.
func (_d *AgentServiceAccountAssignmentDeleteOne) Where(ps ...predicate.AgentServiceAccountAssignment) *AgentServiceAccountAssignmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentServiceAccountAssignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentserviceaccountassignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentServiceAccountAssignmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
