// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agentreincarnation"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// AgentReincarnationDelete is the builder for deleting a AgentReincarnation entity.
type AgentReincarnationDelete struct {
	config
	hooks    []Hook
	mutation *AgentReincarnationMutation
}

// Where appends a list predicates to the AgentReincarnationDelete builder.
func (_d *AgentReincarnationDelete) Where(ps ...predicate.AgentReincarnation) *AgentReincarnationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AgentReincarnationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentReincarnationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AgentReincarnationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agentreincarnation.Table, sqlgraph.NewFieldSpec(agentreincarnation.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AgentReincarnationDeleteOne is the builder for deleting a single AgentReincarnation entity.
type AgentReincarnationDeleteOne struct {
	_d *AgentReincarnationDelete
}

// Where appends a list predicates to the AgentReincarnationDelete builder.
func (_d *AgentReincarnationDeleteOne) Where(ps ...predicate.AgentReincarnation) *AgentReincarnationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AgentReincarnationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agentreincarnation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AgentReincarnationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
