// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grovesyncstate"
)

// GroveSyncState is the model entity for the GroveSyncState schema.
type GroveSyncState struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID string `json:"grove_id,omitempty"`
	// BrokerID holds the value of the "broker_id" field.
	BrokerID string `json:"broker_id,omitempty"`
	// LastSyncTime holds the value of the "last_sync_time" field.
	LastSyncTime *time.Time `json:"last_sync_time,omitempty"`
	// LastCommitSha holds the value of the "last_commit_sha" field.
	LastCommitSha string `json:"last_commit_sha,omitempty"`
	// FileCount holds the value of the "file_count" field.
	FileCount int `json:"file_count,omitempty"`
	// TotalBytes holds the value of the "total_bytes" field.
	TotalBytes   int64 `json:"total_bytes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroveSyncState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grovesyncstate.FieldFileCount, grovesyncstate.FieldTotalBytes:
			values[i] = new(sql.NullInt64)
		case grovesyncstate.FieldID, grovesyncstate.FieldGroveID, grovesyncstate.FieldBrokerID, grovesyncstate.FieldLastCommitSha:
			values[i] = new(sql.NullString)
		case grovesyncstate.FieldLastSyncTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroveSyncState fields.
func (_m *GroveSyncState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grovesyncstate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case grovesyncstate.FieldGroveID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value.Valid {
				_m.GroveID = value.String
			}
		case grovesyncstate.FieldBrokerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field broker_id", values[i])
			} else if value.Valid {
				_m.BrokerID = value.String
			}
		case grovesyncstate.FieldLastSyncTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_time", values[i])
			} else if value.Valid {
				_m.LastSyncTime = new(time.Time)
				*_m.LastSyncTime = value.Time
			}
		case grovesyncstate.FieldLastCommitSha:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_commit_sha", values[i])
			} else if value.Valid {
				_m.LastCommitSha = value.String
			}
		case grovesyncstate.FieldFileCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_count", values[i])
			} else if value.Valid {
				_m.FileCount = int(value.Int64)
			}
		case grovesyncstate.FieldTotalBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_bytes", values[i])
			} else if value.Valid {
				_m.TotalBytes = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroveSyncState.
// This includes values selected through modifiers, order, etc.
func (_m *GroveSyncState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroveSyncState.
// Note that you need to call GroveSyncState.Unwrap() before calling this method if this GroveSyncState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroveSyncState) Update() *GroveSyncStateUpdateOne {
	return NewGroveSyncStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroveSyncState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroveSyncState) Unwrap() *GroveSyncState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroveSyncState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroveSyncState) String() string {
	var builder strings.Builder
	builder.WriteString("GroveSyncState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("grove_id=")
	builder.WriteString(_m.GroveID)
	builder.WriteString(", ")
	builder.WriteString("broker_id=")
	builder.WriteString(_m.BrokerID)
	builder.WriteString(", ")
	if v := _m.LastSyncTime; v != nil {
		builder.WriteString("last_sync_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_commit_sha=")
	builder.WriteString(_m.LastCommitSha)
	builder.WriteString(", ")
	builder.WriteString("file_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileCount))
	builder.WriteString(", ")
	builder.WriteString("total_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalBytes))
	builder.WriteByte(')')
	return builder.String()
}

// GroveSyncStates is a parsable slice of GroveSyncState.
type GroveSyncStates []*GroveSyncState
