// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grovesyncstate"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// GroveSyncStateUpdate is the builder for updating GroveSyncState entities.
type GroveSyncStateUpdate struct {
	config
	hooks    []Hook
	mutation *GroveSyncStateMutation
}

// Where appends a list predicates to the GroveSyncStateUpdate builder.
func (_u *GroveSyncStateUpdate) Where(ps ...predicate.GroveSyncState) *GroveSyncStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroveID sets the "grove_id" field.
func (_u *GroveSyncStateUpdate) SetGroveID(v string) *GroveSyncStateUpdate {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *GroveSyncStateUpdate) SetNillableGroveID(v *string) *GroveSyncStateUpdate {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *GroveSyncStateUpdate) SetBrokerID(v string) *GroveSyncStateUpdate {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *GroveSyncStateUpdate) SetNillableBrokerID(v *string) *GroveSyncStateUpdate {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// SetLastSyncTime sets the "last_sync_time" field.
func (_u *GroveSyncStateUpdate) SetLastSyncTime(v time.Time) *GroveSyncStateUpdate {
	_u.mutation.SetLastSyncTime(v)
	return _u
}

// SetNillableLastSyncTime sets the "last_sync_time" field if the given value is not nil.
func (_u *GroveSyncStateUpdate) SetNillableLastSyncTime(v *time.Time) *GroveSyncStateUpdate {
	if v != nil {
		_u.SetLastSyncTime(*v)
	}
	return _u
}

// ClearLastSyncTime clears the value of the "last_sync_time" field.
func (_u *GroveSyncStateUpdate) ClearLastSyncTime() *GroveSyncStateUpdate {
	_u.mutation.ClearLastSyncTime()
	return _u
}

// SetLastCommitSha sets the "last_commit_sha" field.
func (_u *GroveSyncStateUpdate) SetLastCommitSha(v string) *GroveSyncStateUpdate {
	_u.mutation.SetLastCommitSha(v)
	return _u
}

// SetNillableLastCommitSha sets the "last_commit_sha" field if the given value is not nil.
func (_u *GroveSyncStateUpdate) SetNillableLastCommitSha(v *string) *GroveSyncStateUpdate {
	if v != nil {
		_u.SetLastCommitSha(*v)
	}
	return _u
}

// ClearLastCommitSha clears the value of the "last_commit_sha" field.
func (_u *GroveSyncStateUpdate) ClearLastCommitSha() *GroveSyncStateUpdate {
	_u.mutation.ClearLastCommitSha()
	return _u
}

// SetFileCount sets the "file_count" field.
func (_u *GroveSyncStateUpdate) SetFileCount(v int) *GroveSyncStateUpdate {
	_u.mutation.ResetFileCount()
	_u.mutation.SetFileCount(v)
	return _u
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_u *GroveSyncStateUpdate) SetNillableFileCount(v *int) *GroveSyncStateUpdate {
	if v != nil {
		_u.SetFileCount(*v)
	}
	return _u
}

// AddFileCount adds value to the "file_count" field.
func (_u *GroveSyncStateUpdate) AddFileCount(v int) *GroveSyncStateUpdate {
	_u.mutation.AddFileCount(v)
	return _u
}

// SetTotalBytes sets the "total_bytes" field.
func (_u *GroveSyncStateUpdate) SetTotalBytes(v int64) *GroveSyncStateUpdate {
	_u.mutation.ResetTotalBytes()
	_u.mutation.SetTotalBytes(v)
	return _u
}

// SetNillableTotalBytes sets the "total_bytes" field if the given value is not nil.
func (_u *GroveSyncStateUpdate) SetNillableTotalBytes(v *int64) *GroveSyncStateUpdate {
	if v != nil {
		_u.SetTotalBytes(*v)
	}
	return _u
}

// AddTotalBytes adds value to the "total_bytes" field.
func (_u *GroveSyncStateUpdate) AddTotalBytes(v int64) *GroveSyncStateUpdate {
	_u.mutation.AddTotalBytes(v)
	return _u
}

// Mutation returns the GroveSyncStateMutation object of the builder.
func (_u *GroveSyncStateUpdate) Mutation() *GroveSyncStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroveSyncStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroveSyncStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroveSyncStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroveSyncStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroveSyncStateUpdate) check() error {
	if v, ok := _u.mutation.GroveID(); ok {
		if err := grovesyncstate.GroveIDValidator(v); err != nil {
			return &ValidationError{Name: "grove_id", err: fmt.Errorf(`ent: validator failed for field "GroveSyncState.grove_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GroveSyncStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grovesyncstate.Table, grovesyncstate.Columns, sqlgraph.NewFieldSpec(grovesyncstate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroveID(); ok {
		_spec.SetField(grovesyncstate.FieldGroveID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(grovesyncstate.FieldBrokerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncTime(); ok {
		_spec.SetField(grovesyncstate.FieldLastSyncTime, field.TypeTime, value)
	}
	if _u.mutation.LastSyncTimeCleared() {
		_spec.ClearField(grovesyncstate.FieldLastSyncTime, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCommitSha(); ok {
		_spec.SetField(grovesyncstate.FieldLastCommitSha, field.TypeString, value)
	}
	if _u.mutation.LastCommitShaCleared() {
		_spec.ClearField(grovesyncstate.FieldLastCommitSha, field.TypeString)
	}
	if value, ok := _u.mutation.FileCount(); ok {
		_spec.SetField(grovesyncstate.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileCount(); ok {
		_spec.AddField(grovesyncstate.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalBytes(); ok {
		_spec.SetField(grovesyncstate.FieldTotalBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalBytes(); ok {
		_spec.AddField(grovesyncstate.FieldTotalBytes, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grovesyncstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroveSyncStateUpdateOne is the builder for updating a single GroveSyncState entity.
type GroveSyncStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroveSyncStateMutation
}

// SetGroveID sets the "grove_id" field.
func (_u *GroveSyncStateUpdateOne) SetGroveID(v string) *GroveSyncStateUpdateOne {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *GroveSyncStateUpdateOne) SetNillableGroveID(v *string) *GroveSyncStateUpdateOne {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetBrokerID sets the "broker_id" field.
func (_u *GroveSyncStateUpdateOne) SetBrokerID(v string) *GroveSyncStateUpdateOne {
	_u.mutation.SetBrokerID(v)
	return _u
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_u *GroveSyncStateUpdateOne) SetNillableBrokerID(v *string) *GroveSyncStateUpdateOne {
	if v != nil {
		_u.SetBrokerID(*v)
	}
	return _u
}

// SetLastSyncTime sets the "last_sync_time" field.
func (_u *GroveSyncStateUpdateOne) SetLastSyncTime(v time.Time) *GroveSyncStateUpdateOne {
	_u.mutation.SetLastSyncTime(v)
	return _u
}

// SetNillableLastSyncTime sets the "last_sync_time" field if the given value is not nil.
func (_u *GroveSyncStateUpdateOne) SetNillableLastSyncTime(v *time.Time) *GroveSyncStateUpdateOne {
	if v != nil {
		_u.SetLastSyncTime(*v)
	}
	return _u
}

// ClearLastSyncTime clears the value of the "last_sync_time" field.
func (_u *GroveSyncStateUpdateOne) ClearLastSyncTime() *GroveSyncStateUpdateOne {
	_u.mutation.ClearLastSyncTime()
	return _u
}

// SetLastCommitSha sets the "last_commit_sha" field.
func (_u *GroveSyncStateUpdateOne) SetLastCommitSha(v string) *GroveSyncStateUpdateOne {
	_u.mutation.SetLastCommitSha(v)
	return _u
}

// SetNillableLastCommitSha sets the "last_commit_sha" field if the given value is not nil.
func (_u *GroveSyncStateUpdateOne) SetNillableLastCommitSha(v *string) *GroveSyncStateUpdateOne {
	if v != nil {
		_u.SetLastCommitSha(*v)
	}
	return _u
}

// ClearLastCommitSha clears the value of the "last_commit_sha" field.
func (_u *GroveSyncStateUpdateOne) ClearLastCommitSha() *GroveSyncStateUpdateOne {
	_u.mutation.ClearLastCommitSha()
	return _u
}

// SetFileCount sets the "file_count" field.
func (_u *GroveSyncStateUpdateOne) SetFileCount(v int) *GroveSyncStateUpdateOne {
	_u.mutation.ResetFileCount()
	_u.mutation.SetFileCount(v)
	return _u
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_u *GroveSyncStateUpdateOne) SetNillableFileCount(v *int) *GroveSyncStateUpdateOne {
	if v != nil {
		_u.SetFileCount(*v)
	}
	return _u
}

// AddFileCount adds value to the "file_count" field.
func (_u *GroveSyncStateUpdateOne) AddFileCount(v int) *GroveSyncStateUpdateOne {
	_u.mutation.AddFileCount(v)
	return _u
}

// SetTotalBytes sets the "total_bytes" field.
func (_u *GroveSyncStateUpdateOne) SetTotalBytes(v int64) *GroveSyncStateUpdateOne {
	_u.mutation.ResetTotalBytes()
	_u.mutation.SetTotalBytes(v)
	return _u
}

// SetNillableTotalBytes sets the "total_bytes" field if the given value is not nil.
func (_u *GroveSyncStateUpdateOne) SetNillableTotalBytes(v *int64) *GroveSyncStateUpdateOne {
	if v != nil {
		_u.SetTotalBytes(*v)
	}
	return _u
}

// AddTotalBytes adds value to the "total_bytes" field.
func (_u *GroveSyncStateUpdateOne) AddTotalBytes(v int64) *GroveSyncStateUpdateOne {
	_u.mutation.AddTotalBytes(v)
	return _u
}

// Mutation returns the GroveSyncStateMutation object of the builder.
func (_u *GroveSyncStateUpdateOne) Mutation() *GroveSyncStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the GroveSyncStateUpdate builder.
func (_u *GroveSyncStateUpdateOne) Where(ps ...predicate.GroveSyncState) *GroveSyncStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroveSyncStateUpdateOne) Select(field string, fields ...string) *GroveSyncStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroveSyncState entity.
func (_u *GroveSyncStateUpdateOne) Save(ctx context.Context) (*GroveSyncState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroveSyncStateUpdateOne) SaveX(ctx context.Context) *GroveSyncState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroveSyncStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroveSyncStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroveSyncStateUpdateOne) check() error {
	if v, ok := _u.mutation.GroveID(); ok {
		if err := grovesyncstate.GroveIDValidator(v); err != nil {
			return &ValidationError{Name: "grove_id", err: fmt.Errorf(`ent: validator failed for field "GroveSyncState.grove_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GroveSyncStateUpdateOne) sqlSave(ctx context.Context) (_node *GroveSyncState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grovesyncstate.Table, grovesyncstate.Columns, sqlgraph.NewFieldSpec(grovesyncstate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroveSyncState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grovesyncstate.FieldID)
		for _, f := range fields {
			if !grovesyncstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grovesyncstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroveID(); ok {
		_spec.SetField(grovesyncstate.FieldGroveID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BrokerID(); ok {
		_spec.SetField(grovesyncstate.FieldBrokerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncTime(); ok {
		_spec.SetField(grovesyncstate.FieldLastSyncTime, field.TypeTime, value)
	}
	if _u.mutation.LastSyncTimeCleared() {
		_spec.ClearField(grovesyncstate.FieldLastSyncTime, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCommitSha(); ok {
		_spec.SetField(grovesyncstate.FieldLastCommitSha, field.TypeString, value)
	}
	if _u.mutation.LastCommitShaCleared() {
		_spec.ClearField(grovesyncstate.FieldLastCommitSha, field.TypeString)
	}
	if value, ok := _u.mutation.FileCount(); ok {
		_spec.SetField(grovesyncstate.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFileCount(); ok {
		_spec.AddField(grovesyncstate.FieldFileCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalBytes(); ok {
		_spec.SetField(grovesyncstate.FieldTotalBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalBytes(); ok {
		_spec.AddField(grovesyncstate.FieldTotalBytes, field.TypeInt64, value)
	}
	_node = &GroveSyncState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grovesyncstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
