// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/agent"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grove"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/schema"
	"github.com/google/uuid"
)

// GroveCreate is the builder for creating a Grove entity.
type GroveCreate struct {
	config
	mutation *GroveMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *GroveCreate) SetName(v string) *GroveCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *GroveCreate) SetSlug(v string) *GroveCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetGitRemote sets the "git_remote" field.
func (_c *GroveCreate) SetGitRemote(v string) *GroveCreate {
	_c.mutation.SetGitRemote(v)
	return _c
}

// SetNillableGitRemote sets the "git_remote" field if the given value is not nil.
func (_c *GroveCreate) SetNillableGitRemote(v *string) *GroveCreate {
	if v != nil {
		_c.SetGitRemote(*v)
	}
	return _c
}

// SetLabels sets the "labels" field.
func (_c *GroveCreate) SetLabels(v map[string]string) *GroveCreate {
	_c.mutation.SetLabels(v)
	return _c
}

// SetAnnotations sets the "annotations" field.
func (_c *GroveCreate) SetAnnotations(v map[string]string) *GroveCreate {
	_c.mutation.SetAnnotations(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroveCreate) SetCreatedAt(v time.Time) *GroveCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroveCreate) SetNillableCreatedAt(v *time.Time) *GroveCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GroveCreate) SetUpdatedAt(v time.Time) *GroveCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GroveCreate) SetNillableUpdatedAt(v *time.Time) *GroveCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GroveCreate) SetCreatedBy(v string) *GroveCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GroveCreate) SetNillableCreatedBy(v *string) *GroveCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *GroveCreate) SetOwnerID(v string) *GroveCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *GroveCreate) SetNillableOwnerID(v *string) *GroveCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *GroveCreate) SetVisibility(v string) *GroveCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *GroveCreate) SetNillableVisibility(v *string) *GroveCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetDefaultRuntimeBrokerID sets the "default_runtime_broker_id" field.
func (_c *GroveCreate) SetDefaultRuntimeBrokerID(v uuid.UUID) *GroveCreate {
	_c.mutation.SetDefaultRuntimeBrokerID(v)
	return _c
}

// SetNillableDefaultRuntimeBrokerID sets the "default_runtime_broker_id" field if the given value is not nil.
func (_c *GroveCreate) SetNillableDefaultRuntimeBrokerID(v *uuid.UUID) *GroveCreate {
	if v != nil {
		_c.SetDefaultRuntimeBrokerID(*v)
	}
	return _c
}

// SetSharedDirs sets the "shared_dirs" field.
func (_c *GroveCreate) SetSharedDirs(v []schema.SharedDir) *GroveCreate {
	_c.mutation.SetSharedDirs(v)
	return _c
}

// SetGithubInstallationID sets the "github_installation_id" field.
func (_c *GroveCreate) SetGithubInstallationID(v int64) *GroveCreate {
	_c.mutation.SetGithubInstallationID(v)
	return _c
}

// SetNillableGithubInstallationID sets the "github_installation_id" field if the given value is not nil.
func (_c *GroveCreate) SetNillableGithubInstallationID(v *int64) *GroveCreate {
	if v != nil {
		_c.SetGithubInstallationID(*v)
	}
	return _c
}

// SetGithubPermissions sets the "github_permissions" field.
func (_c *GroveCreate) SetGithubPermissions(v *schema.GitHubTokenPermissions) *GroveCreate {
	_c.mutation.SetGithubPermissions(v)
	return _c
}

// SetGithubAppStatus sets the "github_app_status" field.
func (_c *GroveCreate) SetGithubAppStatus(v *schema.GitHubAppGroveStatus) *GroveCreate {
	_c.mutation.SetGithubAppStatus(v)
	return _c
}

// SetGitIdentity sets the "git_identity" field.
func (_c *GroveCreate) SetGitIdentity(v *schema.GitIdentityConfig) *GroveCreate {
	_c.mutation.SetGitIdentity(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GroveCreate) SetID(v uuid.UUID) *GroveCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GroveCreate) SetNillableID(v *uuid.UUID) *GroveCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAgentIDs adds the "agents" edge to the Agent entity by IDs.
func (_c *GroveCreate) AddAgentIDs(ids ...uuid.UUID) *GroveCreate {
	_c.mutation.AddAgentIDs(ids...)
	return _c
}

// AddAgents adds the "agents" edges to the Agent entity.
func (_c *GroveCreate) AddAgents(v ...*Agent) *GroveCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentIDs(ids...)
}

// Mutation returns the GroveMutation object of the builder.
func (_c *GroveCreate) Mutation() *GroveMutation {
	return _c.mutation
}

// Save creates the Grove in the database.
func (_c *GroveCreate) Save(ctx context.Context) (*Grove, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroveCreate) SaveX(ctx context.Context) *Grove {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroveCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroveCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroveCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grove.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grove.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := grove.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := grove.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroveCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Grove.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := grove.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Grove.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Grove.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := grove.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Grove.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Grove.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Grove.updated_at"`)}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "Grove.visibility"`)}
	}
	return nil
}

func (_c *GroveCreate) sqlSave(ctx context.Context) (*Grove, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroveCreate) createSpec() (*Grove, *sqlgraph.CreateSpec) {
	var (
		_node = &Grove{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grove.Table, sqlgraph.NewFieldSpec(grove.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(grove.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(grove.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.GitRemote(); ok {
		_spec.SetField(grove.FieldGitRemote, field.TypeString, value)
		_node.GitRemote = &value
	}
	if value, ok := _c.mutation.Labels(); ok {
		_spec.SetField(grove.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := _c.mutation.Annotations(); ok {
		_spec.SetField(grove.FieldAnnotations, field.TypeJSON, value)
		_node.Annotations = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grove.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grove.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(grove.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(grove.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(grove.FieldVisibility, field.TypeString, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.DefaultRuntimeBrokerID(); ok {
		_spec.SetField(grove.FieldDefaultRuntimeBrokerID, field.TypeUUID, value)
		_node.DefaultRuntimeBrokerID = &value
	}
	if value, ok := _c.mutation.SharedDirs(); ok {
		_spec.SetField(grove.FieldSharedDirs, field.TypeJSON, value)
		_node.SharedDirs = value
	}
	if value, ok := _c.mutation.GithubInstallationID(); ok {
		_spec.SetField(grove.FieldGithubInstallationID, field.TypeInt64, value)
		_node.GithubInstallationID = &value
	}
	if value, ok := _c.mutation.GithubPermissions(); ok {
		_spec.SetField(grove.FieldGithubPermissions, field.TypeJSON, value)
		_node.GithubPermissions = value
	}
	if value, ok := _c.mutation.GithubAppStatus(); ok {
		_spec.SetField(grove.FieldGithubAppStatus, field.TypeJSON, value)
		_node.GithubAppStatus = value
	}
	if value, ok := _c.mutation.GitIdentity(); ok {
		_spec.SetField(grove.FieldGitIdentity, field.TypeJSON, value)
		_node.GitIdentity = value
	}
	if nodes := _c.mutation.AgentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   grove.AgentsTable,
			Columns: []string{grove.AgentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GroveCreateBulk is the builder for creating many Grove entities in bulk.
type GroveCreateBulk struct {
	config
	err      error
	builders []*GroveCreate
}

// Save creates the Grove entities in the database.
func (_c *GroveCreateBulk) Save(ctx context.Context) ([]*Grove, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Grove, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroveMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroveCreateBulk) SaveX(ctx context.Context) []*Grove {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroveCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroveCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
