// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grovecontributor"
)

// GroveContributor is the model entity for the GroveContributor schema.
type GroveContributor struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID string `json:"grove_id,omitempty"`
	// BrokerID holds the value of the "broker_id" field.
	BrokerID string `json:"broker_id,omitempty"`
	// BrokerName holds the value of the "broker_name" field.
	BrokerName string `json:"broker_name,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Profiles holds the value of the "profiles" field.
	Profiles string `json:"profiles,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen *time.Time `json:"last_seen,omitempty"`
	// LocalPath holds the value of the "local_path" field.
	LocalPath string `json:"local_path,omitempty"`
	// LinkedBy holds the value of the "linked_by" field.
	LinkedBy string `json:"linked_by,omitempty"`
	// LinkedAt holds the value of the "linked_at" field.
	LinkedAt *time.Time `json:"linked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroveContributor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grovecontributor.FieldID, grovecontributor.FieldGroveID, grovecontributor.FieldBrokerID, grovecontributor.FieldBrokerName, grovecontributor.FieldMode, grovecontributor.FieldStatus, grovecontributor.FieldProfiles, grovecontributor.FieldLocalPath, grovecontributor.FieldLinkedBy:
			values[i] = new(sql.NullString)
		case grovecontributor.FieldLastSeen, grovecontributor.FieldLinkedAt, grovecontributor.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroveContributor fields.
func (_m *GroveContributor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grovecontributor.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case grovecontributor.FieldGroveID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value.Valid {
				_m.GroveID = value.String
			}
		case grovecontributor.FieldBrokerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field broker_id", values[i])
			} else if value.Valid {
				_m.BrokerID = value.String
			}
		case grovecontributor.FieldBrokerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field broker_name", values[i])
			} else if value.Valid {
				_m.BrokerName = value.String
			}
		case grovecontributor.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case grovecontributor.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case grovecontributor.FieldProfiles:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profiles", values[i])
			} else if value.Valid {
				_m.Profiles = value.String
			}
		case grovecontributor.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = new(time.Time)
				*_m.LastSeen = value.Time
			}
		case grovecontributor.FieldLocalPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_path", values[i])
			} else if value.Valid {
				_m.LocalPath = value.String
			}
		case grovecontributor.FieldLinkedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field linked_by", values[i])
			} else if value.Valid {
				_m.LinkedBy = value.String
			}
		case grovecontributor.FieldLinkedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field linked_at", values[i])
			} else if value.Valid {
				_m.LinkedAt = new(time.Time)
				*_m.LinkedAt = value.Time
			}
		case grovecontributor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroveContributor.
// This includes values selected through modifiers, order, etc.
func (_m *GroveContributor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroveContributor.
// Note that you need to call GroveContributor.Unwrap() before calling this method if this GroveContributor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroveContributor) Update() *GroveContributorUpdateOne {
	return NewGroveContributorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroveContributor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroveContributor) Unwrap() *GroveContributor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroveContributor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroveContributor) String() string {
	var builder strings.Builder
	builder.WriteString("GroveContributor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("grove_id=")
	builder.WriteString(_m.GroveID)
	builder.WriteString(", ")
	builder.WriteString("broker_id=")
	builder.WriteString(_m.BrokerID)
	builder.WriteString(", ")
	builder.WriteString("broker_name=")
	builder.WriteString(_m.BrokerName)
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("profiles=")
	builder.WriteString(_m.Profiles)
	builder.WriteString(", ")
	if v := _m.LastSeen; v != nil {
		builder.WriteString("last_seen=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("local_path=")
	builder.WriteString(_m.LocalPath)
	builder.WriteString(", ")
	builder.WriteString("linked_by=")
	builder.WriteString(_m.LinkedBy)
	builder.WriteString(", ")
	if v := _m.LinkedAt; v != nil {
		builder.WriteString("linked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GroveContributors is a parsable slice of GroveContributor.
type GroveContributors []*GroveContributor
