// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/grovesyncstate"
)

// GroveSyncStateCreate is the builder for creating a GroveSyncState entity.
type GroveSyncStateCreate struct {
	config
	mutation *GroveSyncStateMutation
	hooks    []Hook
}

// SetGroveID sets the "grove_id" field.
func (_c *GroveSyncStateCreate) SetGroveID(v string) *GroveSyncStateCreate {
	_c.mutation.SetGroveID(v)
	return _c
}

// SetBrokerID sets the "broker_id" field.
func (_c *GroveSyncStateCreate) SetBrokerID(v string) *GroveSyncStateCreate {
	_c.mutation.SetBrokerID(v)
	return _c
}

// SetNillableBrokerID sets the "broker_id" field if the given value is not nil.
func (_c *GroveSyncStateCreate) SetNillableBrokerID(v *string) *GroveSyncStateCreate {
	if v != nil {
		_c.SetBrokerID(*v)
	}
	return _c
}

// SetLastSyncTime sets the "last_sync_time" field.
func (_c *GroveSyncStateCreate) SetLastSyncTime(v time.Time) *GroveSyncStateCreate {
	_c.mutation.SetLastSyncTime(v)
	return _c
}

// SetNillableLastSyncTime sets the "last_sync_time" field if the given value is not nil.
func (_c *GroveSyncStateCreate) SetNillableLastSyncTime(v *time.Time) *GroveSyncStateCreate {
	if v != nil {
		_c.SetLastSyncTime(*v)
	}
	return _c
}

// SetLastCommitSha sets the "last_commit_sha" field.
func (_c *GroveSyncStateCreate) SetLastCommitSha(v string) *GroveSyncStateCreate {
	_c.mutation.SetLastCommitSha(v)
	return _c
}

// SetNillableLastCommitSha sets the "last_commit_sha" field if the given value is not nil.
func (_c *GroveSyncStateCreate) SetNillableLastCommitSha(v *string) *GroveSyncStateCreate {
	if v != nil {
		_c.SetLastCommitSha(*v)
	}
	return _c
}

// SetFileCount sets the "file_count" field.
func (_c *GroveSyncStateCreate) SetFileCount(v int) *GroveSyncStateCreate {
	_c.mutation.SetFileCount(v)
	return _c
}

// SetNillableFileCount sets the "file_count" field if the given value is not nil.
func (_c *GroveSyncStateCreate) SetNillableFileCount(v *int) *GroveSyncStateCreate {
	if v != nil {
		_c.SetFileCount(*v)
	}
	return _c
}

// SetTotalBytes sets the "total_bytes" field.
func (_c *GroveSyncStateCreate) SetTotalBytes(v int64) *GroveSyncStateCreate {
	_c.mutation.SetTotalBytes(v)
	return _c
}

// SetNillableTotalBytes sets the "total_bytes" field if the given value is not nil.
func (_c *GroveSyncStateCreate) SetNillableTotalBytes(v *int64) *GroveSyncStateCreate {
	if v != nil {
		_c.SetTotalBytes(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GroveSyncStateCreate) SetID(v string) *GroveSyncStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GroveSyncStateMutation object of the builder.
func (_c *GroveSyncStateCreate) Mutation() *GroveSyncStateMutation {
	return _c.mutation
}

// Save creates the GroveSyncState in the database.
func (_c *GroveSyncStateCreate) Save(ctx context.Context) (*GroveSyncState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroveSyncStateCreate) SaveX(ctx context.Context) *GroveSyncState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroveSyncStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroveSyncStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroveSyncStateCreate) defaults() {
	if _, ok := _c.mutation.BrokerID(); !ok {
		v := grovesyncstate.DefaultBrokerID
		_c.mutation.SetBrokerID(v)
	}
	if _, ok := _c.mutation.FileCount(); !ok {
		v := grovesyncstate.DefaultFileCount
		_c.mutation.SetFileCount(v)
	}
	if _, ok := _c.mutation.TotalBytes(); !ok {
		v := grovesyncstate.DefaultTotalBytes
		_c.mutation.SetTotalBytes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroveSyncStateCreate) check() error {
	if _, ok := _c.mutation.GroveID(); !ok {
		return &ValidationError{Name: "grove_id", err: errors.New(`ent: missing required field "GroveSyncState.grove_id"`)}
	}
	if v, ok := _c.mutation.GroveID(); ok {
		if err := grovesyncstate.GroveIDValidator(v); err != nil {
			return &ValidationError{Name: "grove_id", err: fmt.Errorf(`ent: validator failed for field "GroveSyncState.grove_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BrokerID(); !ok {
		return &ValidationError{Name: "broker_id", err: errors.New(`ent: missing required field "GroveSyncState.broker_id"`)}
	}
	if _, ok := _c.mutation.FileCount(); !ok {
		return &ValidationError{Name: "file_count", err: errors.New(`ent: missing required field "GroveSyncState.file_count"`)}
	}
	if _, ok := _c.mutation.TotalBytes(); !ok {
		return &ValidationError{Name: "total_bytes", err: errors.New(`ent: missing required field "GroveSyncState.total_bytes"`)}
	}
	return nil
}

func (_c *GroveSyncStateCreate) sqlSave(ctx context.Context) (*GroveSyncState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GroveSyncState.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroveSyncStateCreate) createSpec() (*GroveSyncState, *sqlgraph.CreateSpec) {
	var (
		_node = &GroveSyncState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grovesyncstate.Table, sqlgraph.NewFieldSpec(grovesyncstate.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GroveID(); ok {
		_spec.SetField(grovesyncstate.FieldGroveID, field.TypeString, value)
		_node.GroveID = value
	}
	if value, ok := _c.mutation.BrokerID(); ok {
		_spec.SetField(grovesyncstate.FieldBrokerID, field.TypeString, value)
		_node.BrokerID = value
	}
	if value, ok := _c.mutation.LastSyncTime(); ok {
		_spec.SetField(grovesyncstate.FieldLastSyncTime, field.TypeTime, value)
		_node.LastSyncTime = &value
	}
	if value, ok := _c.mutation.LastCommitSha(); ok {
		_spec.SetField(grovesyncstate.FieldLastCommitSha, field.TypeString, value)
		_node.LastCommitSha = value
	}
	if value, ok := _c.mutation.FileCount(); ok {
		_spec.SetField(grovesyncstate.FieldFileCount, field.TypeInt, value)
		_node.FileCount = value
	}
	if value, ok := _c.mutation.TotalBytes(); ok {
		_spec.SetField(grovesyncstate.FieldTotalBytes, field.TypeInt64, value)
		_node.TotalBytes = value
	}
	return _node, _spec
}

// GroveSyncStateCreateBulk is the builder for creating many GroveSyncState entities in bulk.
type GroveSyncStateCreateBulk struct {
	config
	err      error
	builders []*GroveSyncStateCreate
}

// Save creates the GroveSyncState entities in the database.
func (_c *GroveSyncStateCreateBulk) Save(ctx context.Context) ([]*GroveSyncState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroveSyncState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroveSyncStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroveSyncStateCreateBulk) SaveX(ctx context.Context) []*GroveSyncState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroveSyncStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroveSyncStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
