// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/messagerecord"
)

// MessageRecord is the model entity for the MessageRecord schema.
type MessageRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID string `json:"grove_id,omitempty"`
	// Sender holds the value of the "sender" field.
	Sender string `json:"sender,omitempty"`
	// SenderID holds the value of the "sender_id" field.
	SenderID string `json:"sender_id,omitempty"`
	// Recipient holds the value of the "recipient" field.
	Recipient string `json:"recipient,omitempty"`
	// RecipientID holds the value of the "recipient_id" field.
	RecipientID string `json:"recipient_id,omitempty"`
	// Msg holds the value of the "msg" field.
	Msg string `json:"msg,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Urgent holds the value of the "urgent" field.
	Urgent bool `json:"urgent,omitempty"`
	// Broadcasted holds the value of the "broadcasted" field.
	Broadcasted bool `json:"broadcasted,omitempty"`
	// Read holds the value of the "read" field.
	Read bool `json:"read,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID string `json:"agent_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessageRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messagerecord.FieldUrgent, messagerecord.FieldBroadcasted, messagerecord.FieldRead:
			values[i] = new(sql.NullBool)
		case messagerecord.FieldID, messagerecord.FieldGroveID, messagerecord.FieldSender, messagerecord.FieldSenderID, messagerecord.FieldRecipient, messagerecord.FieldRecipientID, messagerecord.FieldMsg, messagerecord.FieldType, messagerecord.FieldAgentID:
			values[i] = new(sql.NullString)
		case messagerecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessageRecord fields.
func (_m *MessageRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messagerecord.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case messagerecord.FieldGroveID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value.Valid {
				_m.GroveID = value.String
			}
		case messagerecord.FieldSender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender", values[i])
			} else if value.Valid {
				_m.Sender = value.String
			}
		case messagerecord.FieldSenderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = value.String
			}
		case messagerecord.FieldRecipient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient", values[i])
			} else if value.Valid {
				_m.Recipient = value.String
			}
		case messagerecord.FieldRecipientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_id", values[i])
			} else if value.Valid {
				_m.RecipientID = value.String
			}
		case messagerecord.FieldMsg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field msg", values[i])
			} else if value.Valid {
				_m.Msg = value.String
			}
		case messagerecord.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case messagerecord.FieldUrgent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field urgent", values[i])
			} else if value.Valid {
				_m.Urgent = value.Bool
			}
		case messagerecord.FieldBroadcasted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field broadcasted", values[i])
			} else if value.Valid {
				_m.Broadcasted = value.Bool
			}
		case messagerecord.FieldRead:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field read", values[i])
			} else if value.Valid {
				_m.Read = value.Bool
			}
		case messagerecord.FieldAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = value.String
			}
		case messagerecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessageRecord.
// This includes values selected through modifiers, order, etc.
func (_m *MessageRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MessageRecord.
// Note that you need to call MessageRecord.Unwrap() before calling this method if this MessageRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MessageRecord) Update() *MessageRecordUpdateOne {
	return NewMessageRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MessageRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MessageRecord) Unwrap() *MessageRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessageRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MessageRecord) String() string {
	var builder strings.Builder
	builder.WriteString("MessageRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("grove_id=")
	builder.WriteString(_m.GroveID)
	builder.WriteString(", ")
	builder.WriteString("sender=")
	builder.WriteString(_m.Sender)
	builder.WriteString(", ")
	builder.WriteString("sender_id=")
	builder.WriteString(_m.SenderID)
	builder.WriteString(", ")
	builder.WriteString("recipient=")
	builder.WriteString(_m.Recipient)
	builder.WriteString(", ")
	builder.WriteString("recipient_id=")
	builder.WriteString(_m.RecipientID)
	builder.WriteString(", ")
	builder.WriteString("msg=")
	builder.WriteString(_m.Msg)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("urgent=")
	builder.WriteString(fmt.Sprintf("%v", _m.Urgent))
	builder.WriteString(", ")
	builder.WriteString("broadcasted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Broadcasted))
	builder.WriteString(", ")
	builder.WriteString("read=")
	builder.WriteString(fmt.Sprintf("%v", _m.Read))
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(_m.AgentID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MessageRecords is a parsable slice of MessageRecord.
type MessageRecords []*MessageRecord
