// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/messagerecord"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/predicate"
)

// MessageRecordUpdate is the builder for updating MessageRecord entities.
type MessageRecordUpdate struct {
	config
	hooks    []Hook
	mutation *MessageRecordMutation
}

// Where appends a list predicates to the MessageRecordUpdate builder.
func (_u *MessageRecordUpdate) Where(ps ...predicate.MessageRecord) *MessageRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroveID sets the "grove_id" field.
func (_u *MessageRecordUpdate) SetGroveID(v string) *MessageRecordUpdate {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableGroveID(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetSender sets the "sender" field.
func (_u *MessageRecordUpdate) SetSender(v string) *MessageRecordUpdate {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableSender(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *MessageRecordUpdate) SetSenderID(v string) *MessageRecordUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableSenderID(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *MessageRecordUpdate) SetRecipient(v string) *MessageRecordUpdate {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableRecipient(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *MessageRecordUpdate) SetRecipientID(v string) *MessageRecordUpdate {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableRecipientID(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetMsg sets the "msg" field.
func (_u *MessageRecordUpdate) SetMsg(v string) *MessageRecordUpdate {
	_u.mutation.SetMsg(v)
	return _u
}

// SetNillableMsg sets the "msg" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableMsg(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetMsg(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MessageRecordUpdate) SetType(v string) *MessageRecordUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableType(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetUrgent sets the "urgent" field.
func (_u *MessageRecordUpdate) SetUrgent(v bool) *MessageRecordUpdate {
	_u.mutation.SetUrgent(v)
	return _u
}

// SetNillableUrgent sets the "urgent" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableUrgent(v *bool) *MessageRecordUpdate {
	if v != nil {
		_u.SetUrgent(*v)
	}
	return _u
}

// SetBroadcasted sets the "broadcasted" field.
func (_u *MessageRecordUpdate) SetBroadcasted(v bool) *MessageRecordUpdate {
	_u.mutation.SetBroadcasted(v)
	return _u
}

// SetNillableBroadcasted sets the "broadcasted" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableBroadcasted(v *bool) *MessageRecordUpdate {
	if v != nil {
		_u.SetBroadcasted(*v)
	}
	return _u
}

// SetRead sets the "read" field.
func (_u *MessageRecordUpdate) SetRead(v bool) *MessageRecordUpdate {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableRead(v *bool) *MessageRecordUpdate {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *MessageRecordUpdate) SetAgentID(v string) *MessageRecordUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *MessageRecordUpdate) SetNillableAgentID(v *string) *MessageRecordUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// Mutation returns the MessageRecordMutation object of the builder.
func (_u *MessageRecordUpdate) Mutation() *MessageRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageRecordUpdate) check() error {
	if v, ok := _u.mutation.GroveID(); ok {
		if err := messagerecord.GroveIDValidator(v); err != nil {
			return &ValidationError{Name: "grove_id", err: fmt.Errorf(`ent: validator failed for field "MessageRecord.grove_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sender(); ok {
		if err := messagerecord.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "MessageRecord.sender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Recipient(); ok {
		if err := messagerecord.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "MessageRecord.recipient": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagerecord.Table, messagerecord.Columns, sqlgraph.NewFieldSpec(messagerecord.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroveID(); ok {
		_spec.SetField(messagerecord.FieldGroveID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(messagerecord.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(messagerecord.FieldSenderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(messagerecord.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientID(); ok {
		_spec.SetField(messagerecord.FieldRecipientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Msg(); ok {
		_spec.SetField(messagerecord.FieldMsg, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(messagerecord.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urgent(); ok {
		_spec.SetField(messagerecord.FieldUrgent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Broadcasted(); ok {
		_spec.SetField(messagerecord.FieldBroadcasted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(messagerecord.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(messagerecord.FieldAgentID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageRecordUpdateOne is the builder for updating a single MessageRecord entity.
type MessageRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageRecordMutation
}

// SetGroveID sets the "grove_id" field.
func (_u *MessageRecordUpdateOne) SetGroveID(v string) *MessageRecordUpdateOne {
	_u.mutation.SetGroveID(v)
	return _u
}

// SetNillableGroveID sets the "grove_id" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableGroveID(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetGroveID(*v)
	}
	return _u
}

// SetSender sets the "sender" field.
func (_u *MessageRecordUpdateOne) SetSender(v string) *MessageRecordUpdateOne {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableSender(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *MessageRecordUpdateOne) SetSenderID(v string) *MessageRecordUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableSenderID(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *MessageRecordUpdateOne) SetRecipient(v string) *MessageRecordUpdateOne {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableRecipient(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *MessageRecordUpdateOne) SetRecipientID(v string) *MessageRecordUpdateOne {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableRecipientID(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetMsg sets the "msg" field.
func (_u *MessageRecordUpdateOne) SetMsg(v string) *MessageRecordUpdateOne {
	_u.mutation.SetMsg(v)
	return _u
}

// SetNillableMsg sets the "msg" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableMsg(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetMsg(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MessageRecordUpdateOne) SetType(v string) *MessageRecordUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableType(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetUrgent sets the "urgent" field.
func (_u *MessageRecordUpdateOne) SetUrgent(v bool) *MessageRecordUpdateOne {
	_u.mutation.SetUrgent(v)
	return _u
}

// SetNillableUrgent sets the "urgent" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableUrgent(v *bool) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetUrgent(*v)
	}
	return _u
}

// SetBroadcasted sets the "broadcasted" field.
func (_u *MessageRecordUpdateOne) SetBroadcasted(v bool) *MessageRecordUpdateOne {
	_u.mutation.SetBroadcasted(v)
	return _u
}

// SetNillableBroadcasted sets the "broadcasted" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableBroadcasted(v *bool) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetBroadcasted(*v)
	}
	return _u
}

// SetRead sets the "read" field.
func (_u *MessageRecordUpdateOne) SetRead(v bool) *MessageRecordUpdateOne {
	_u.mutation.SetRead(v)
	return _u
}

// SetNillableRead sets the "read" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableRead(v *bool) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetRead(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *MessageRecordUpdateOne) SetAgentID(v string) *MessageRecordUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *MessageRecordUpdateOne) SetNillableAgentID(v *string) *MessageRecordUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// Mutation returns the MessageRecordMutation object of the builder.
func (_u *MessageRecordUpdateOne) Mutation() *MessageRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageRecordUpdate builder.
func (_u *MessageRecordUpdateOne) Where(ps ...predicate.MessageRecord) *MessageRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageRecordUpdateOne) Select(field string, fields ...string) *MessageRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessageRecord entity.
func (_u *MessageRecordUpdateOne) Save(ctx context.Context) (*MessageRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageRecordUpdateOne) SaveX(ctx context.Context) *MessageRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageRecordUpdateOne) check() error {
	if v, ok := _u.mutation.GroveID(); ok {
		if err := messagerecord.GroveIDValidator(v); err != nil {
			return &ValidationError{Name: "grove_id", err: fmt.Errorf(`ent: validator failed for field "MessageRecord.grove_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sender(); ok {
		if err := messagerecord.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "MessageRecord.sender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Recipient(); ok {
		if err := messagerecord.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "MessageRecord.recipient": %w`, err)}
		}
	}
	return nil
}

func (_u *MessageRecordUpdateOne) sqlSave(ctx context.Context) (_node *MessageRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagerecord.Table, messagerecord.Columns, sqlgraph.NewFieldSpec(messagerecord.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagerecord.FieldID)
		for _, f := range fields {
			if !messagerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroveID(); ok {
		_spec.SetField(messagerecord.FieldGroveID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(messagerecord.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(messagerecord.FieldSenderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(messagerecord.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipientID(); ok {
		_spec.SetField(messagerecord.FieldRecipientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Msg(); ok {
		_spec.SetField(messagerecord.FieldMsg, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(messagerecord.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urgent(); ok {
		_spec.SetField(messagerecord.FieldUrgent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Broadcasted(); ok {
		_spec.SetField(messagerecord.FieldBroadcasted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Read(); ok {
		_spec.SetField(messagerecord.FieldRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(messagerecord.FieldAgentID, field.TypeString, value)
	}
	_node = &MessageRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
