// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GoogleCloudPlatform/scion/pkg/ent/notificationsubscription"
)

// NotificationSubscription is the model entity for the NotificationSubscription schema.
type NotificationSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID *string `json:"agent_id,omitempty"`
	// SubscriberType holds the value of the "subscriber_type" field.
	SubscriberType string `json:"subscriber_type,omitempty"`
	// SubscriberID holds the value of the "subscriber_id" field.
	SubscriberID string `json:"subscriber_id,omitempty"`
	// GroveID holds the value of the "grove_id" field.
	GroveID string `json:"grove_id,omitempty"`
	// TriggerActivities holds the value of the "trigger_activities" field.
	TriggerActivities string `json:"trigger_activities,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy    string `json:"created_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationsubscription.FieldID, notificationsubscription.FieldScope, notificationsubscription.FieldAgentID, notificationsubscription.FieldSubscriberType, notificationsubscription.FieldSubscriberID, notificationsubscription.FieldGroveID, notificationsubscription.FieldTriggerActivities, notificationsubscription.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case notificationsubscription.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationSubscription fields.
func (_m *NotificationSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationsubscription.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case notificationsubscription.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case notificationsubscription.FieldAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = new(string)
				*_m.AgentID = value.String
			}
		case notificationsubscription.FieldSubscriberType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscriber_type", values[i])
			} else if value.Valid {
				_m.SubscriberType = value.String
			}
		case notificationsubscription.FieldSubscriberID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscriber_id", values[i])
			} else if value.Valid {
				_m.SubscriberID = value.String
			}
		case notificationsubscription.FieldGroveID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field grove_id", values[i])
			} else if value.Valid {
				_m.GroveID = value.String
			}
		case notificationsubscription.FieldTriggerActivities:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_activities", values[i])
			} else if value.Valid {
				_m.TriggerActivities = value.String
			}
		case notificationsubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notificationsubscription.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationSubscription.
// Note that you need to call NotificationSubscription.Unwrap() before calling this method if this NotificationSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationSubscription) Update() *NotificationSubscriptionUpdateOne {
	return NewNotificationSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationSubscription) Unwrap() *NotificationSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	if v := _m.AgentID; v != nil {
		builder.WriteString("agent_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("subscriber_type=")
	builder.WriteString(_m.SubscriberType)
	builder.WriteString(", ")
	builder.WriteString("subscriber_id=")
	builder.WriteString(_m.SubscriberID)
	builder.WriteString(", ")
	builder.WriteString("grove_id=")
	builder.WriteString(_m.GroveID)
	builder.WriteString(", ")
	builder.WriteString("trigger_activities=")
	builder.WriteString(_m.TriggerActivities)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// NotificationSubscriptions is a parsable slice of NotificationSubscription.
type NotificationSubscriptions []*NotificationSubscription
