// Code generated by ent, DO NOT EDIT.

package messagerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the messagerecord type in the database.
	Label = "message_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroveID holds the string denoting the grove_id field in the database.
	FieldGroveID = "grove_id"
	// FieldSender holds the string denoting the sender field in the database.
	FieldSender = "sender"
	// FieldSenderID holds the string denoting the sender_id field in the database.
	FieldSenderID = "sender_id"
	// FieldRecipient holds the string denoting the recipient field in the database.
	FieldRecipient = "recipient"
	// FieldRecipientID holds the string denoting the recipient_id field in the database.
	FieldRecipientID = "recipient_id"
	// FieldMsg holds the string denoting the msg field in the database.
	FieldMsg = "msg"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldUrgent holds the string denoting the urgent field in the database.
	FieldUrgent = "urgent"
	// FieldBroadcasted holds the string denoting the broadcasted field in the database.
	FieldBroadcasted = "broadcasted"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the messagerecord in the database.
	Table = "messages"
)

// Columns holds all SQL columns for messagerecord fields.
var Columns = []string{
	FieldID,
	FieldGroveID,
	FieldSender,
	FieldSenderID,
	FieldRecipient,
	FieldRecipientID,
	FieldMsg,
	FieldType,
	FieldUrgent,
	FieldBroadcasted,
	FieldRead,
	FieldAgentID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GroveIDValidator is a validator for the "grove_id" field. It is called by the builders before save.
	GroveIDValidator func(string) error
	// SenderValidator is a validator for the "sender" field. It is called by the builders before save.
	SenderValidator func(string) error
	// DefaultSenderID holds the default value on creation for the "sender_id" field.
	DefaultSenderID string
	// RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	RecipientValidator func(string) error
	// DefaultRecipientID holds the default value on creation for the "recipient_id" field.
	DefaultRecipientID string
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// DefaultUrgent holds the default value on creation for the "urgent" field.
	DefaultUrgent bool
	// DefaultBroadcasted holds the default value on creation for the "broadcasted" field.
	DefaultBroadcasted bool
	// DefaultRead holds the default value on creation for the "read" field.
	DefaultRead bool
	// DefaultAgentID holds the default value on creation for the "agent_id" field.
	DefaultAgentID string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the MessageRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroveID orders the results by the grove_id field.
func ByGroveID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroveID, opts...).ToFunc()
}

// BySender orders the results by the sender field.
func BySender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSender, opts...).ToFunc()
}

// BySenderID orders the results by the sender_id field.
func BySenderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderID, opts...).ToFunc()
}

// ByRecipient orders the results by the recipient field.
func ByRecipient(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipient, opts...).ToFunc()
}

// ByRecipientID orders the results by the recipient_id field.
func ByRecipientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientID, opts...).ToFunc()
}

// ByMsg orders the results by the msg field.
func ByMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMsg, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByUrgent orders the results by the urgent field.
func ByUrgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUrgent, opts...).ToFunc()
}

// ByBroadcasted orders the results by the broadcasted field.
func ByBroadcasted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBroadcasted, opts...).ToFunc()
}

// ByRead orders the results by the read field.
func ByRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRead, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
