apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scion

configMapGenerator:
  - name: scion-settings
    files:
      - settings.yaml

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - state-pvc.yaml
  - deployment.yaml
  - service.yaml
